### ISSUE TITLE
NBA 2k25/NBA 2k26 GPU Driver crash

### ISSUE THREAD

**Issue by davidwalgenbach** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#1209]
### Requirements

- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates)
- [x] Game is not cracked, modded and use the latest patch

### Game

NBA 2k26

### Game acquisition link

https://store.steampowered.com/app/3472040/NBA_2K26/

### Game Platform

Steam

### Processor / Processor Number

Intel core 7 ultra 258v

### Graphic Card

Intel arc 140v

### GPU Driver Version

32.0.101.7028

### Rendering API

DirectX 12

### Windows Build

Windows 11 24H2

### Intel System Support Utility report

https://drive.google.com/uc?export=download&id=1FJ_ykFfLkJMZmrzoGz53__MipdGY_cDN

### Description and steps to reproduce

Play a mycareer game or try to load into my career mode. After playing the game for some amount of time 20 mins to 45 mins the game will crash the display "GPU failed with error code 0x887a0006".

### Game graphic quality *

- [ ] Low
- [ ] Medium
- [x] High
- [ ] Ultra

### Game resolution

1920x1080

### Game VSync

On

### Game display mode

Fullscreen

### Detailed game settings

Settings don't seem to matter. I've tried to run the game with a mix of all settings. Happens in 2k25 and 2k26.

### Device / Platform name

MSI Claw 8 ai+

**Comment by bumpkin0624** [comment]
Maybe this helps.
https://droplink.digital/file/0a4bd138a03edad34a4f75c18a707e36

**Comment by BiZkViT96** [comment]
@IGCIT remove comment above. bumpkin0624 Joined 4 hours ago, "fix" archive automatically downloads and triger Microsoft Defender. Not to mention, he gave no explanation of what is inside and how it would help.

Worth checking https://steamcommunity.com/app/2878980/discussions/0/6679490060456044358/

**Comment by subiedaveee** [comment]
Yeah this seems to be a problem that's affected AMD NVIDIA and the Intel cards. AMD and Nvidia have fixed it with driver updates from some of the forums I've read.

**Comment by Arturo-Intel** [comment]
@davidwalgenbach 
Thanks for sharing this issue,
We will notify you if we have any questions or news

--r2

**Comment by mujeeb-intel** [comment]
Thanks for letting us know @davidwalgenbach Let me try reproducing this issue. Ill get back to you.

**Comment by subiedaveee** [comment]
If it helps, I believe I attached a crash dump/memory dump in the Google drive link I provided.

> Thanks for letting us know @davidwalgenbach Let me try reproducing this issue. Ill get back to you.

**Comment by mujeeb-intel** [comment]
Much appreciated.

**Comment by subiedaveee** [comment]
Any updates on this or more info required?

**Comment by mujeeb-intel** [comment]
No, I havent gotten the chance, but I'll be reproducing this today. I will let you know.

**Comment by wodnerpie** [comment]
Yeah I also have this issue. Quite at random, the game will crash with that exact same error code
Here's one of the logs:
```
Windows

Description
Faulting Application Path: C:\Windows\System32\WerFault.exe
Creation Time: 05/09/2025 18:45:49
Problem: Erreur matérielle
Status: Rapport mis en file d'attente

Problem signature
Problem Event Name:           LiveKernelEvent
Code:                         141
Paramètre 1:                  ffffb68023d4c010
Paramètre 2:                  fffff8054a602b20
Paramètre 3:                  0
Paramètre 4:                  ffffb68015fca0c0
Version du système d’exploitation: 10_0_26100
Service Pack:                 0_0
Produit :                     768_1

Extra information about the problem
Bucket ID: (18446744073709551615)

Files that help describe the problem
WATCHDOG-20250905-1845.dmp
sysdata.xml
WERInternalMetadata.xml
memory.csv
sysinfo.txt
WERInternalRequest.xml
```

I have linked the Intel SSU:

[Intel SSU 05.09.2025.txt](https://github.com/user-attachments/files/22176029/Intel.SSU.05.09.2025.txt)

Also the game performs insanely bad.
With an Ultra Core 185H (and Integrated Intel Arc Graphics), at everything set to lowest and XeSS set to Ultra Performance, I'm having like 25-35 FPS in the City (while drawing like 50W which is HUGE for this CPU/GPU)

**Comment by mujeeb-intel** [comment]
@subiedaveee how long did it take for you to load the shaders?

**Comment by subiedaveee** [comment]
@mujeeb-intel It takes quite a long time. Probably about an hour/hour and a half ish. I chose to load all shaders.

**Comment by mujeeb-intel** [comment]
@subiedaveee  okay, I reproduced it. 

I do want to say that the game's minimum requirements state it needs a580, which has 24xe cores. The ARC 140V GPU has 8 Xe Cores which makes this not compatible. 

Now, I wanted to see if there could be any workaround to this crashing issue, so I increased the amount of RAM used as VRAM in IGS to 70% and the game did not crash for me. Could you try this? If not 70% then maybe, you can try 87%?

Overall this game will not be compatible with the ARC 140V but I hope the workaround will fix the crashing issue

**Comment by mujeeb-intel** [comment]
Okay nvm, the game just crashed for me even after setting the ram to 75%

**Comment by subiedaveee** [comment]
@mujeeb-intel 

I will try that tonight. The game runs great which is why it's super perplexing that it crashes out of the blue. Last time I had tried to run 2k25 was with 70% allocated to vram iirc. Does the error message stated not indicate some sort of error in a function the driver is calling? The only reason I ask this is because this same crash has affected AMD and Nvidia cards in the past and was fixed with a driver update.

**Comment by subiedaveee** [comment]
@mujeeb-intel for reference: https://steamcommunity.com/app/2878980/discussions/0/6679490060456044358/?l=latam&ctp=7

**Comment by mujeeb-intel** [comment]
"...most likely because of an invalid command passed by the calling application" This one right? Yup same error.

I don't want to give you false hope about getting this issue resolved on this GPU. However, next week I’ll work with the debug team to determine whether there's a solution or if they'll simply reject it, citing incompatibility. I’ll also review the Steam link you shared regarding the AMD issue that was addressed through their driver with them.

Hang tight. @subiedaveee

**Comment by subiedaveee** [comment]
@mujeeb-intel 

Thank you very much! That's the exact error. If it's a compatibility thing that's unfortunate but the error, how well the game runs prior to the crash (it even runs on my steam deck lol), and some of the responses to things I've seen online regarding downgrading drivers or waiting for a fix for specific drivers makes me think it could be something driver related. I appreciate the time you're taking to look into this. There's quite a bit of people on the MSI Claw subreddit that are looking forward to a fix for this as well.

**Comment by jan-jm93** [comment]
Turning off Hardware-Accelerated GPU Scheduling in Windows fixes this issue

**Comment by subiedaveee** [comment]
This does not fix the issue. Just had the same crash after trying this setting after playing for 10 minutes. 

> Turning off Hardware-Accelerated GPU Scheduling in Windows fixes this issue

**Comment by mujeeb-intel** [comment]
Hey @subiedaveee the bug has been reported internally for this application. I will get back to you as soon as I learn anything new. Hang tight, please.

**Comment by mujeeb-intel** [comment]
BUG ID: 14025864744

**Comment by subiedaveee** [comment]
@mujeeb-intel 

Thank you very much, I appreciate your help! Regarding the bug ID, can that be used to track progress?

**Comment by mujeeb-intel** [comment]
No problem. Yes that's correct.

**Comment by subiedaveee** [comment]
@mujeeb-intel okay awesome. Is there a different repository I should be looking at then with that bug ID? (Sorry for so many questions haha).

**Comment by mujeeb-intel** [comment]
> @mujeeb-intel okay awesome. Is there a different repository I should be looking at then with that bug ID? (Sorry for so many questions haha).

I'm just following this current one. So I don't really know about others. This is where I'll be sharing all the new updates. And no worries.

**Comment by javierlga** [comment]
Any updates about this issue? Thanks.

**Comment by subiedaveee** [comment]
Any updates? Thanks again for looking into this.

**Comment by mujeeb-intel** [comment]
> Any updates? Thanks again for looking into this.

Hi. It's in work in progress. I'll notify you here with any new updates.

**Comment by subiedaveee** [comment]
> > Any updates? Thanks again for looking into this.
> 
> Hi. It's in work in progress. I'll notify you here with any new updates.

Thank you very much! Looking forward to positive results

**Comment by BiZkViT96** [comment]
New 32.0.101.8132 WHQL driver has this in [changelog](https://downloadmirror.intel.com/865175/ReleaseNotes_101.8132.pdf)

Fixed Issues

Intel Core Ultra Series 2 with built-in Intel Arc GPUs:
NBA 2K26 (DX12) may experience an application crash during gameplay.

**Comment by mujeeb-intel** [comment]
Sweet, yeah I was going to say at the time I left a response. The driver was already out. Thanks for testing. I'll go ahead and close this case.

**Comment by subiedaveee** [comment]
> Sweet, yeah I was going to say at the time I left a response. The driver was already out. Thanks for testing. I'll go ahead and close this case.

@mujeeb-intel 

Sorry to report but the game unfortunately still crashes. Don't see the error code from before this time but I just had a crash after playing my career for about 6 minutes. Event viewer just shows a generic "Application Hang" log.

**Comment by kluuuwu** [comment]
I am still having the same error code in 2K26 after installing the latest driver. In games my framerate is mostly over 100 but it will still crash a few minutes in. I am currently using a 285H CPU with Arc 140T.

**Comment by BiZkViT96** [comment]
@mujeeb-intel Read my message again. I haven't tested anything. You closed the issue too soon.
