### ISSUE TITLE
EA FC 26 - Freezes, Stutters & FPS Drops.

### ISSUE THREAD

**Issue by GodrixZA** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#1232]
### Requirements

- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates)
- [x] Game is not cracked, modded and use the latest patch

### Game

EA FC 26

### Game acquisition link

https://store.steampowered.com/app/3405690/EA_SPORTS_FC_26/

### Game Platform

EA app

### Processor / Processor Number

AMD Ryzen 5 - 7500F

### Graphic Card

Intel Arc - B570

### GPU Driver Version

32.0.101.7029

### Rendering API

DirectX 12

### Windows Build

Windows 11 24H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/22425377/igcit_ssu.txt)

### Description and steps to reproduce

Hi,

**_Issue:_**
FPS will tank to what feels like 1 FPS, causing almost a mini-freeze like stutter effect for about up to max 5 seconds and then everything goes back to normal. 

This is highly annoying and from what I've seen, watching other streamers using either "AMD" or "NVIDIA", this looks to be an "INTEL" only issue. 

I've rolled back to Driver ...7026 for testing as well and same thing occurs. I have tested both "Fullscreen" and "Borderless", "VSync On or Off", "GSync On or Off" doesn't matter same issue persists. "Graphics Quality - Low or Ultra" again same thing. I've basically exhausted all graphical combinations and same issue persists.

"Rebar On or Off" no difference as well, same with "HAGS" and "Game Mode" within Win 11. Nothing made a difference. 

So whatever seems to be causing this huge FPS tank, in my case from 240+ FPS to what seems and feels like 1 FPS, seems very weird.

**NB:**
- This seems to mainly occur during transitions, if that makes any sense.
- Also noted shaders, after multiple restarts seem to still be compiling albeit way shorter than on first initial launch. Unsure if this is normal behaviour.

**Reproduce:**
- Open a "Bronze Pack" in the "store" and the issue I've mentioned will occur.

- **_EDIT:_** Play any game and when loading in right at the start of the game, the same thing will occur.
- **_EDIT:_** Occurs during halftime and seems to be occurring during most transitions and or cutscenes.

### Game graphic quality

Low

### Game resolution

1080p

### Game VSync

On

### Game display mode

Borderless Windowed

### Detailed game settings

Please refer to "Description and steps to reproduce" where I've clearly outlined which setting and combinations I've tested, which like I've said is all of it and nothing changes.

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/4f627886-e2c8-48a6-97ce-72dd4e139f24" />

### Device / Platform name

PC

**Comment by GodrixZA** [comment]
https://www.reddit.com/r/EASportsFC/comments/1nkp1g4/frame_rate_drops_to_1_fps_during/

**Comment by Seneken** [comment]
Same here, I'm on B580 and latest driver 7029. The game is stutters every new match, menu, after haft-time. After few seconds, it becomes smooth and can playable. It would be really frustrating and unfair if I were the opponent have the ball first. By the time the screen stops stuttering, my opponent is already at my goal.


quote from an comment on Reddit:
"the same issue here, cutscenes, going into game pause in menus or when opening the packs, huge fps drops and fps spikes - I have not found any fix... ultra performance power plan does not help, fps limit does not help, vsync does not help... basically nothing helps.... Installed fresh Windows drivers all... nothing helps... I don't get why this fps spikes drop to 2, 3 FPS"

**Comment by binsi13** [comment]
Same here:

Running the latest "32.0.101.7026" I get with my **B580** hard FPS drops (down to 1) in Ultimate Team in different situations: moments start, pack openings, rivals match starts....

CPU is **AMD Ryzen 7 9700X**.

I tried borderless window, fullscreen, Vsync oin/off, details low/mid/max, etc....doesnt change a lot.

After 5-15 seconds within a match the frame rate normalizes.

**Comment by Karen-Intel** [comment]
Hi guys, thank you for your report and the confirmation of the issue
We've already added it to our queue. We'll report back as soon as we check it (can be me or someone else on our side), but we'll keep you posted

Karen

**Comment by GodrixZA** [comment]
> Hi guys, thank you for your report and the confirmation of the issue We've already added it to our queue. We'll report back as soon as we check it (can be me or someone else on our side), but we'll keep you posted
> 
> Karen

Hi, any idea when we can expect a fix?

**Comment by Seneken** [comment]
> > Hi guys, thank you for your report and the confirmation of the issue We've already added it to our queue. We'll report back as soon as we check it (can be me or someone else on our side), but we'll keep you posted
> > Karen
> 
> Hi, any idea when we can expect a fix?

I think we can relax and wait—the Intel driver team has been doing great, addressing user-reported issues quickly. Updates are released quite timely.

**Comment by Seneken** [comment]
Today EA release the new update patch for FC26, seem it is fixed all stutters issue for all GPU card brand. I will test and report soon.  
ps: I’ve noticed some commands from AMD and Nvidia card users face similar issues, so it’s likely EA’s game optimization fault rather than the GPU driver.

**Comment by binsi13** [comment]
> Today EA release the new update patch for FC26, seem it is fixed all stutters issue for all GPU card brand. I will test and report soon. ps: I’ve noticed some commands from AMD and Nvidia card users face similar issues, so it’s likely EA’s game optimization fault rather than the GPU driver.

Didn't fix it for me. 
If anyone sees improvements, please share your settings.

**Comment by GodrixZA** [comment]
> > Today EA release the new update patch for FC26, seem it is fixed all stutters issue for all GPU card brand. I will test and report soon. ps: I’ve noticed some commands from AMD and Nvidia card users face similar issues, so it’s likely EA’s game optimization fault rather than the GPU driver.
> 
> Didn't fix it for me. If anyone sees improvements, please share your settings.

Correct, also not fixed here. As I stated initially in my post, this isn't a "game" issue but a manufacturer issue because I have not seen streamers I watch with either AMD or Nvidia cards have this issue.

**Comment by Seneken** [comment]
> > > Today EA release the new update patch for FC26, seem it is fixed all stutters issue for all GPU card brand. I will test and report soon. ps: I’ve noticed some commands from AMD and Nvidia card users face similar issues, so it’s likely EA’s game optimization fault rather than the GPU driver.
> > 
> > 
> > Didn't fix it for me. If anyone sees improvements, please share your settings.
> 
> Correct, also not fixed here. As I stated initially in my post, this isn't a "game" issue but a manufacturer issue because I have not seen streamers I watch with either AMD or Nvidia cards have this issue.

Confirmed, EA update patch not fixed this issue, must wait for an fix by Intel's driver.

**Comment by binsi13** [comment]
@Arturo-Intel  Any progress on this issue already? Is it something Intel is going to fix, or is it a EA task?

**Comment by Seneken** [comment]
We have new driver here(32.0.101.8135), but not see any mention fix for FC26. 
I will test for the game and report later. Hope all things are fixed ;)


Update: the issue still NOT fixed.
Update2: After DDU and fresh install, use full screen mode and Auto on all setting. The game is smoothing now.

**Comment by binsi13** [comment]
@Seneken Can you please share your Full Settings from the Video-Screen in FC 26? Vsync On/Off?

I did DDU cleanup , fresh lateste driver install (including the Intel Graphics Software), FC26 Graphics Auto all, in FC26 Fullscreen, 2k resolution, 144Hz and Vsync On. 

Also borderless windows mode and Vsync Off doesnt improve it.

I still get stuttering when starting a test game, e.g. Rush.

**Comment by GodrixZA** [comment]
> We have new driver here(32.0.101.8135), but not see any mention fix for FC26. I will test for the game and report later. Hope all things are fixed ;)
> 
> Update: the issue still NOT fixed. Update2: After DDU and fresh install, use full screen mode and Auto on all setting. The game is smoothing now.

Can confirm still not fixed here either.

**Comment by binsi13** [comment]
New Intel Arc Driver doesn't improve the situation.

**Comment by GodrixZA** [comment]
Still not fixed after latest update.

**Comment by Seneken** [comment]
> [@Seneken](https://github.com/Seneken) Can you please share your Full Settings from the Video-Screen in FC 26? Vsync On/Off?
> 
> I did DDU cleanup , fresh lateste driver install (including the Intel Graphics Software), FC26 Graphics Auto all, in FC26 Fullscreen, 2k resolution, 144Hz and Vsync On.
> 
> Also borderless windows mode and Vsync Off doesnt improve it.
> 
> I still get stuttering when starting a test game, e.g. Rush.

Sorry for my previous comment, I confirmed the issue still not fixed. 
Now I have to down all setting to LOW and using Windows mode. These settings make decrease stutters fps drops in game on my system.

**Comment by Gabriela-Intel** [comment]
Hey everyone, thanks for all the updates and for checking in! Sorry it’s taken a bit to follow up. 

I’ve confirmed I’m seeing the same issue on FC26 and will be flagging it to the right team for investigation.

Just to set expectations, please don’t assume a fix is available unless we’ve announced one. We don’t have an ETA or further details to share at this time.

Thanks again for your patience and for helping us track this down :)

**Comment by Seneken** [comment]
It's been over a month since the game was released, and Arc B5xx users are still reporting stuttering and FPS drop issues — yet there’s no update to fix them.

We play this game every day, so I really hope Intel releases an optimized update soon. 
Thanks Intel team a lot.

**Comment by GodrixZA** [comment]
> It's been over a month since the game was released, and Arc B5xx users are still reporting stuttering and FPS drop issues — yet there’s no update to fix them.
> 
> We play this game every day, so I really hope Intel releases an optimized update soon. Thanks Intel team a lot.

I concur.

**Comment by Gabriela-Intel** [comment]
Rest assured that we're looking at this issue. I'll share an update once I have something to share.

**Comment by binsi13** [comment]
It's just an AAA title every year. So no worries, take your time. /s

**Comment by binsi13** [comment]
With the newest driver (from today), the latest FC 26 patch (also today) and a manual cleanup of the shaders (C:\Users\[USER]\AppData\Locallow\Intel\ShaderCache)...the effect seems better...just a littl stuttering left.

**Comment by Seneken** [comment]
Yeah, stuttering and fps drop is reduced. Now I can enjoy the game without annoying.
thanks Intel's driver team.

**Comment by GodrixZA** [comment]
Slightly better, but main issue still persists.

**Comment by strawgit** [comment]
The issue isn't gone for me. I understand that the B580 has its limits, but this doesn't seem to be related to that at all.

**Comment by Seneken** [comment]
__

> The issue isn't gone for me. I understand that the B580 has its limits, but this doesn't seem to be related to that at all.

No, B580 handle well this game, I think you should to use DDU to uninstall your Intel driver, then fresh install 32.0.101.8247 driver. The game will create new shader cache and work well.

I have done the same as I mention above and the game plays smooth on 2k monitor with Medium set.

**Comment by George-Intel** [comment]
Hello @GodrixZA ,

Apologies for the long delay, but wanted to checkin and see if your reported issue is still present with the latest drivers?  
[https://www.intel.com/content/www/us/en/download/785597/intel-arc-graphics-windows.html](url)
