### ISSUE TITLE
Call of Duty Cold War Can't Be Played on ARC

### ISSUE THREAD

**Issue by JohnnyTex** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#188]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Call of Duty Black Ops: Cold War

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 12600k

### Graphic Card [Required]

ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3802 (*latest*)
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[SecondSSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10136475/SecondSSU.txt)

### Description and steps to reproduce [Required]

The game typically won't even boot; I'll try to start the game up and then it'll crash, giving me a GPU related error code. Sometimes I'll actually be able to load into the game, but then it'll eventually crash during shader compilation. I'm assuming ARC isn't even supported on this game, because when I try to turn on the in-game GPU telemetry it tells me the GPU is at 0 degrees. Then the game will eventually crash again w/ a GPU related error code. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560 x 1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

The crashing occurs no matter the settings. I've booted the game up in safe mode (which turns everything to low and medium settings), I've tried setting things to my usual high and ultra settings, and the game (if it even boots to begin w/) will inevitably crash.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
Thanks for contacting Intel, can you attach the screenshot or video recorded for this issue while our system setup is ready to verify?

**Comment by JohnnyTex** [comment]
![20221202_230210](https://user-images.githubusercontent.com/77827332/205424743-5018271c-f336-42be-b4fa-eb0909abe1f1.jpg)

**Comment by JohnnyTex** [comment]
This message is the thing that keeps popping up whenever I try to boot the game. For the record, I'm on the latest driver. For everything.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,
there is new Beta version released [Intel® Arc™ Graphics Windows* DCH Driver - BETA](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html) 31.0.101.3959. can you have a try?

**Comment by JohnnyTex** [comment]
I'm afraid the beta drivers have not fixed the issue. Others in the ARC Discord have previously reported this exact same issue, so I'm gonna ask them to see if they have had any better luck w/ this driver.

**Comment by JohnnyTex** [comment]
I can confirm that another user has confirmed that the new driver also didn't solve the issue for him. He has the exact same issue as me; gets to the shader compilation and then it crashes. That's assuming it even gets that far.

**Comment by JohnnyTex** [comment]
Understood. Makes me wish I never even bothered w/ that feature.

**Comment by IntelSupport-Rozilah** [comment]
hi @JohnnyTex,

The case has been verified on our side and we are able to reproduce it with our configurations as below:
Issue reproduce on(Platform):   ADL-S(i7-12700K)
Graphics device: Arc A770 
Graphics Driver : 31.0.101.3959
Operating System : Windows 11 22H2(22621)
We will be working on a fix. I want to give you a heads-up that the fix may take 3 to 6 months to be included.

**Comment by JohnnyTex** [comment]
You have my thanks for this work! Let's hope for the speediest remedy.

**Comment by JohnnyTex** [comment]
Let me know if I should close this now or keep it open for when the fix is to be announced.

**Comment by IGCIT** [comment]
> Let me know if I should close this now or keep it open for when the fix is to be announced.

close it when issue has been solved, this is informative for those who come here and have the same issue

**Comment by JohnnyTex** [comment]
Seeing that compatibility w/ Modern Warfare II (2022) was resolved in Driver v. 4123, I'd like to know if it also fixed compatibility w/ Cold War? Has there been any update on this one so far? I'd reinstall Cold War myself, but that game is pretty big and I'm short on space, so if I was gonna reinstall it it'd be to finally return to it for real.

**Comment by JohnnyTex** [comment]
Has any progress been made? I miss this game.

**Comment by DoragonHunter** [comment]
I can confirm from my side the Arc Driver Beta 31.0.101.4311 has fixed the crashes and the game is now playable on this driver,  although artificing still happens for movies/cutscene but does not affect gameplay. This update is being pushed through the Intel Driver Support Assistant (IDSA) - Intel Website Driver Link is Broken Currently.

https://downloadmirror.intel.com/776400/gfx_win_101.4311.exe
https://downloadmirror.intel.com/776400/ReleaseNotes_101.4311_BETA.pdf

**Comment by IGCIT** [comment]
@DoragonHunter please open a new issue for the graphical glitches, thanks

**Comment by JohnnyTex** [comment]
I'm reinstalling as we speak! If CW truly has been fixed, then 4311 truly is the miracle driver!

**Comment by JohnnyTex** [comment]
I forgot to update this on Github, but yes! Cold War is _finally_ playable again on ARC! It's definitely got its performance issues, but I consider this issue closed.
