### ISSUE TITLE
Mafia II (Classic): bugs with light, vertex explosion(?) and crashes

### ISSUE THREAD

**Issue by BiZkViT96** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#423]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Mafia II (Classic) update5A

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [X] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12500

### Graphic Card [Required]

UHD 770

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12307260/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Mafia II (Classic) comes bundled with Mafia II: Definitive Edition, at least gogdb still claims like that.

So, the game has a series of issues and all of them occur no matter of settings.. Let's start with the light bug. It's hard to explain, but the game seems to have problems with depth. Many light sources produce a flash when they appear on the screen, including those that shouldnt be visible.

Load Jimmy's Vendetta save (saves attached) and drive to the marker on the map.
![mafia2_2023_08_10_05_01_07_672](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/1534977e-c9e3-4812-b6f2-7155ff6c9ee3)
![mafia2_2023_08_10_02_22_41_183](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/baabd5bd-27a9-45c9-b884-4dd9b913687c)

This is how bug looks like.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/ac3f5644-654e-4e12-8767-141040de475b

That's a light sources INSIDE of the building.

Alternatively, you can start chapter Home Sweet Home from main story.
Here's what it looks like when driving around the city at night.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/29efc588-91e7-49f4-a47d-dafc61ea2ecb

Additional example

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/dbde05dc-b995-4931-8f28-108b6eac6e47

Unfortunately that's not all. There is this thing. Once you saw that, you screwed - render thread of the game will crash soon. Image will freeze then screen become black and sound effects will continue playing. What interesting is that game and driver does not crash. If game locked itself at black screen you can try alt-tab and game will continue to run, but with black screen of course.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/47200eac-667f-4b5c-87dd-b625ffe465dd

Yep, black screen at the end is what im talking about.

I found one spot in the game where I kinda can reproduce this bug. Load Jimmy's Vendetta save and drive to the marker on the map.
![mafia2_2023_08_10_04_27_40_929](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/259ae209-de22-485d-9758-db8f9bdaca21)

When you will be close to factory, bug should appear. It works maybe 2 out of 5 times, so it may take a time. Restart whole game if bug dosent appear and drive to the marker again.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/ad6da2d1-f290-46cb-9707-9197a11ea6c1

In terms of crashes you should also try The Betrayal of Jimmy story. For me the game crashes (2 out of 2) during the
 first mission.

### Game graphic quality [Required]

- [X] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![mafia2_2023_08_10_02_22_02_338](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/c52a044e-e5f0-4691-94d3-77b69878f741)

### Save game

Drop in C:\Users\*USERNAME*\AppData\Local
[2K Games.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12307330/2K.Games.zip)

**Comment by BiZkViT96** [comment]
31.0.101.4644 introduced new bug with shadows. Bug exists no matter of settings. This is was recorded on Low preset.


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/340567ef-98bf-4f42-936d-2c4f020065d7


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/61c958d1-cdb6-4505-aeb8-d3ddca939ecb

**Comment by Ilya-intel** [comment]
Hey @BiZkViT96 ,
I tried this game and couldn't find any of the reported issues (see below).
So I recommend to clean the existing drivers using DDU and install latest one from here:  https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

![Mafia2-1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/f57c8793-6335-47a7-81ff-6b1f592cd149)

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/9854f30b-428c-493d-87c1-fe91ce25e012


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/d148fe98-4056-475f-a435-07a9c7f6f1c0

**Comment by BiZkViT96** [comment]
@Ilya-intel Hi! I can see the FPS in the upper left corner and you get that much on UHD 770? And you sure that you tested the classic version of the game?

**Comment by Ilya-intel** [comment]
@BiZkViT96 
Hehe, I tested on Arc A770.
I'll need to retest with integrated one :D

**Comment by BiZkViT96** [comment]
@Ilya-intel I just checked 4676 driver on High preset and all the problems are the same, except for the shadows, which are now displayed correctly. I couldn't get to the factory, the game crashed driver before I saw the graphics bug.

**Comment by Ilya-intel** [comment]
@BiZkViT96 
Yep, I can see this now.
I'll report it to the driver team and keep you updated.

**Comment by BiZkViT96** [comment]
@IGCIT Replicated.

**Comment by Ilya-intel** [comment]
@BiZkViT96 
FYI Bug ID for this issue: 18033587143.
I'll keep you updated here.

**Comment by BiZkViT96** [comment]
@Ilya-intel Thanks for not abandoning the issue. Sadly only bug with light sources was fixed.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/468eb90a-4e35-4df9-ad63-859253008bf5

I guess you was just lucky. I still can easily replicate "vertex explosion" and crash.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/ac178ff1-0a48-4aeb-9fba-0ba7dfd1c34e


https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/5d8b9b31-62f4-4f68-9c89-e05247d7a528

Settings is still the same.
![mafia2_2024_06_18_05_01_33_988](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/88586431/6d40ff58-311e-42ad-b826-4a452c50e5c6)

**Comment by Ilya-intel** [comment]
@BiZkViT96 
Interesting, let me play some more and get back to you.

**Comment by Ilya-intel** [comment]
@BiZkViT96 
After further testing I still don't see glitches in those special places in the game. Could you try running DDU and install [latest 101.5592](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) driver?
![20240625121748_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/143084944/4af276ed-1988-40a2-9071-c66b19a077e2)

**Comment by BiZkViT96** [comment]
@Ilya-intel Just to be sure, you test iGPU UHD 770?

I will update the driver later this week and let you know the results.

**Comment by Ilya-intel** [comment]
@BiZkViT96 
Same system that had the issue before :)

**Comment by Ilya-intel** [comment]
@BiZkViT96 
Ok, so another system just keeps crashing after 2 minutes.
I'll check with developers regarding this.

**Comment by BiZkViT96** [comment]
@Ilya-intel As promised, I have tested the latest driver - 5592. Loaded chapter "Enemy of the state" from the main story, walked out of the building, saw a small "vertex explosion", game then crashed. BTW: Game crashed during shader compilation on 1 try.

**Comment by BiZkViT96** [comment]
Hi @Ilya-intel ! Thank you for update. I played the game for an hour and found no issues. The game now works stable and without any graphical bugs.
