### ISSUE TITLE
Fan ramping up at idle after 4644 install

### ISSUE THREAD

**Issue by abrfilho** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#430]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows

### Processor / Processor Number [Required]

AMD Ryzen 5 5600

### Graphic Card [Required]

Acer Predator Bifrost A770

### GPU Driver Version [Required]

- [X] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12354032/igcit_ssu.txt)

### Description and steps to reproduce [Required]

After the 4644 update, the fan started an unusual behavior at idle, it starts to ramp up to around 40% then go down to 20%, during game it acts normal or fixing the fan, it acts normal.
Trying to solve the problem, I noticed that at Intel Arc Control Fan Curve adjustment there's now five steps for fan adjustment instead of ten, which was present before the update.

Edit: The ten steps reappeared, but the unusual behavior persists and is happenning inside more demanding tasks too, the temperatura is still normal, but the noise is very annoying.
Fixing the fan speed didn't helped, it just stays longer without going down to 20%.

Edit2: The problem seems to be firmware related. Acer Predator Bifrost have an unusual design, two types of fan, and this issue was only reported by Acer Predator Bifrost owners after the firmware update.

### Device / Platform

Acer Predator Bifrost A770

**Comment by IGCIT** [comment]
please try a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html), and do a reboot after installing the driver

**Comment by abrfilho** [comment]
> please try a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html), and do a reboot after installing the driver

I did it now, same behavior as before, the GPU stays with this unusual fan behavior even inside BIOS.

**Comment by BiZkViT96** [comment]
Thats probably because the driver updated GPU firmware. 

**"it also upgrades the firmware on some Intel Arc graphics cards. This latest version brings stability improvements, better fan behavior, bug fixes, and better compatibility with HDMI connections."**

**Comment by abrfilho** [comment]
> Thats probably because the driver updated GPU firmware.
> 
> **"it also upgrades the firmware on some Intel Arc graphics cards. This latest version brings stability improvements, better fan behavior, bug fixes, and better compatibility with HDMI connections."**

Yes, I imagined that, but now, sadly, I have worse fan behavior

**Comment by Arturo-Intel** [comment]
@abrfilho but it is really a bad behavior? or it is just very noisy? 

-- r2

**Comment by abrfilho** [comment]
> @abrfilho but it is really a bad behavior? or it is just very noisy?
> 
> -- r2

Slightly higher temperatures during heavy workloads, slightly lower at idle due to the higher RPM.
Noisy and annoying at idle due to fan ramping up to 40% and going down afterwards.

I took a quick log from GPU-Z to show the fan  behavior:
[GPU-Z Sensor Log.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12361317/GPU-Z.Sensor.Log.txt)

**Comment by Arturo-Intel** [comment]
> Slightly higher temperatures during heavy workloads, slightly lower at idle due to the higher RPM.
Noisy and annoying at idle due to fan ramping up to 40% and going down afterwards.

Ok, I need to replicate it in my lab.
Thank you for the log

-- r2

**Comment by Arturo-Intel** [comment]
Also, did 4644 update your v-bios? @abrfilho

**Comment by abrfilho** [comment]
> Also, did 4644 update your v-bios? @abrfilho

Yes, updated.
I don't remember which version I had before.
And just to reinforce, my model is the Predator Bifrost A770 OC from Acer, the fan behave like that independent from which preset I choose related to the fan.

**Comment by abrfilho** [comment]
TL:DR

The problem is when the fan operates with a value between 0% and 30%, Predator Bifrost have a minimum value of 20%, making the fan operate at 0% or 30%.

Full text:

I was discussing with someone in reddit who had the same problem, we figured it out that the fan now can't be set at a value between 0% and 30%, if the value is below 30%, the fan will go to zero, but with the standard fan curve and the idle temperature, the fan will go to 0% then 30% instead of keeping a value between, the minimum speed inside Predator Bifrost app is 20%, the standard Bifrost fan curve is shown at the image below.

<img width="479" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/54344422/d2d96ff6-7b6d-4a67-b89d-249c0f837f9e">

There's an increase of ~8,33°C (15°F) at each step, the regular idle temperature here is 40°C (104°F) with fan on.
I'm testing some fan curves to see if I can reach a quieter idle behavior, but with the fan off here, the temperature easily go to 55°C+ (131°F), around the 5th step, ramping  the fan to 30%, my case doesn't have an intake below the GPU, making it impossible to keep lower temperatures at idle.

**Comment by szmigieldesign** [comment]
Sadly, I can confirm the same behavior in my build with Acer's A770 16GB. It was ok prior to .4644. 

I have 3 fans in the front of my PC, one in the back and two at the top (AIO) and I'm unable to keep the A770 from turning its fan on and off unless I disable fans entirely. 

Also, because the card draws ~32W at idle, it's impossible to keep it cool at 0 RPM.

It also seems that the card can't do less than ~1600 RPM now?

**Comment by Jasp2023** [comment]
Hi, Joined to say my Acer A770 Bifrost now also does the same behaviour, going between off and on, the behaviour can also be reproduced in the computers bios so looks to be linked with the firmware update overwriting Acers potentially.

**Comment by szmigieldesign** [comment]
For reference:

[GPU-Z main](https://e.pcloud.link/publink/show?code=XZ7YoBZdIwj90QOxDBlk7Vsq9uorS2yD0S7)
[GPU-Z sensors](https://e.pcloud.link/publink/show?code=XZoQoBZG5Y7nHDCCgYQLliewvHK6QFJgk00)

Also did a clean installation with DDU.

**Comment by Susie1818** [comment]
I second this issue. My Acer Predator BiFrost A770 now also revs fan up and down (up to ~1500rpm and down to 0rpm) when set at 30% fan speed in Arc Control. It is boviously due to the firmware (V-BIOS) update from 20.1053.0 to 20.1064.0 included this latest driver 31.0.101.4644 update. There is definitely something wrong in this new V-BIOS regarding controlling the fan PWM.

**Comment by paulwangabc** [comment]
> Sadly, I can confirm the same behavior in my build with Acer's A770 16GB. It was ok prior to .4644.
> 
> I have 3 fans in the front of my PC, one in the back and two at the top (AIO) and I'm unable to keep the A770 from turning its fan on and off unless I disable fans entirely.
> 
> Also, because the card draws ~32W at idle, it's impossible to keep it cool at 0 RPM.
> 
> It also seems that the card can't do less than ~1600 RPM now?

Do you have iGfx enabled?
Can you disable iGfx and try again?

**Comment by szmigieldesign** [comment]
@paulwangabc if you're referring to integrated GFX then I don't have any as I'm running on i5-13600KF.

**Comment by fulford** [comment]
Experiencing the exact same behaviour. No changes made to system other than updated graphics driver/firmware, now GPU seems unable to find a happy medium where it can stay cool without ramping the fan up and down at idle. Tried tweaking the fan curve, but without actual values for temperature on the X axis this is difficult! (Maybe that could be a future improvement in ARC Control!)
Exact same GPU/CPU combo as OP - and no integrated graphics on my AMD processor.

**Comment by Gam3cat** [comment]
Seeing the same issue on Acer A770 with latest vbios, very annoying as it cycles constantly where previously it was great. 

The funny thing is this fan start/stop issue used to occur on the Asrock A750 until this latest vbios... but seems the fix for that just moved the issue from one card to the other.

Is vbios identifying vendor and setting expected fan curve/settings separately, or is one setting being applied to all which may explain above?

Has this been reproduced and is there a fix in progress?

**Comment by fjamesprice** [comment]
Same issue here with the Acer A770 since upgrading to 31.0.101.4644 two days ago.  
For those who prefer a quieter environment when not gaming, I have found that setting the first three nodes in the fan curve settings to 0% keeps things reasonable, albeit at slightly higher temperatures in the mid 50s.  
With these settings, the fans spin up every five to ten seconds or so, as opposed to being stuck at 30% (loud IMO) and spinning down every five to ten seconds.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134095787/f1274a1f-2f5a-41d2-b52e-4d7fe43da3eb)

Previously, these settings allowed the card to run around 50C when idle, and the fans would spin at lower speeds that would not be distracting while working, reading, etc.

**Comment by Susie1818** [comment]
> ![](https://user-images.githubusercontent.com/134095787/261859811-f1274a1f-2f5a-41d2-b52e-4d7fe43da3eb.png)
Previously, these settings allowed the card to run around 50C when idle, and the fans would spin at lower speeds that would not be distracting while working, reading, etc.

Yes, I second that. Fact is: the fan speed used to be able to be stable around 20%(~1200rpm) or even 15%(~900rpm), but now it cannot even be stable at 30%(~1500rpm). Please fix this issue as soon as possible.

**Comment by dodou89** [comment]
Just to confirm I also have the same issue. Just adding here to ensure the post keeps active.

**Comment by GottaSlay** [comment]
Same issue here on my Acer A770.

**Comment by fjamesprice** [comment]
31.0.101.4669 does not address this issue.

**Comment by szmigieldesign** [comment]
Is there anything being done with this issue?

**Comment by Arturo-Intel** [comment]
This issue is one of the top priority for our dev teams, they are working on this as we speak
We understand the frustration this causes, but rest assured we share and push all your comments to our dev teams.

We will share any news through this thread
Thank you for you patience
--r2

**Comment by felipin58** [comment]
Intel is aware of a fan speed issue impacting some users. We are working to release an updated Intel® Arc™ Graphics driver that resolves the issue this month.

**Comment by Felipe-Intel** [comment]
Intel is aware of a fan speed issue impacting some users. We are working to release an updated Intel® Arc™ Graphics driver that resolves the issue this month.

**Comment by Karen-Intel** [comment]
Hey guys! Can you please test our drivers latest[version](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)? It includes the fixes we were waiting for. Please report back as soon as possible, ty!

Karen

**Comment by abrfilho** [comment]
> Hey guys! Can you please test our drivers latest [version](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)? It includes the fixes we were waiting for. Please report back as soon as possible, ty!
> 
> Karen

Hello Karen, thanks for the hard work!

It seems fixed! I think this hybrid design from Acer gave a little headache to the team (and to me too with the noise 😅)

There was an Arc Control update too, I think this update changed something regarding the fan curve, if you see my comment
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/430#issuecomment-1681073403
I was able to import the fan curve with 10 steps from Predator Bifrost app, now I can't and only have the 6 steps from Intel Arc Control, and the Acer one started at 20%.
Is there a reason to block the fan curve to go below 30%? And is there a way to increase more steps?

**Comment by GottaSlay** [comment]
Seems to be fixed :)

**Comment by fjamesprice** [comment]
The issue isn't quite fixed for me.  Setting Fan Speed Control to Automatic in ARC Control keeps the fans at 30% minimum, which is louder than it was previously at idle with custom fan curve settings.  Manually adjusting the fan curve gives the same results or worse now.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134095787/1155a285-a489-4643-a7c9-dd2afe2a3553)
These settings make the fans pulse every 3-5 seconds with the GPU at 46 degrees.  Before 4644, the fans were capable of idling between 0 and 30%, which is still not possible with today's update.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/134095787/f104be22-5c5f-4c8a-9139-3f39606ba727)
These settings pulse the fans about every 10 seconds, with the GPU around 55 degrees.  As stated previously, before 4644 these settings would allow the fans to run slower while keeping the GPU around 50 degrees.

If we were able to set the fan curve nodes to a percentage between 0 and 30, this might not be a problem at all.  It seems arbitrary to disable control below 30%.

**Comment by Susie1818** [comment]
Only partly fixed.

The "Automatic" option is fixed as it now operates in the same way as the original stock firmware, idle fan speed running around 1200 RPM (fluctuating 10xx~13xx, which is the same behavior as original).

Fan behavior below 20% in "Fan Curve" option has not been fixed. I am pretty sure with the original stock firmware and certain older versions of Arc Control, the actual fan speed could be configured and running at several hundreds RPM stable, which was the settings I used to use, similar to this one posted by [fjamesprice](https://github.com/fjamesprice):

> ![image](https://user-images.githubusercontent.com/134095787/267841957-1155a285-a489-4643-a7c9-dd2afe2a3553.png) 
These settings make the fans pulse every 3-5 seconds with the GPU at 46 degrees.

Ever since certain version of Arc Control (I can't confirm exactly which version but I guess it was driver 101.4575), fan behavior started to be unable to stablize below 20%, ramping up and down (to 0 RPM). I didn't report the issue at that time because I chose to bear with it and adjusted my fan curve to stay all the way on the 30% line from 25°C to 55°C (or at least the "Automatic" option still worked, even though I didn't use it) so that the fan didn't ramp up and down. However, I did post a feature request in the Arc customer support forum that the Fan Curve option in the Arc Control to allow configuration down to 20% instead of 30% because the noise level when it ran around 1500 RPM (30%) was quite noticeably higher.

It was the driver update 101.4644 (with the firmware 20.1064.0) that made it worse (fan behavior just couldn't even stablize at 30%) and thus triggered many people to report the issue (fan speed ramping up and down) here.

Hopefully this issue can get further fixes. Ideally, the fan should be able to work at least down to 15% or even 10% because it indeed used to be able to do that and I had been expericing that for many months until certain version of Arc Control changed it. Alternatively, if intel devs don't think it is safe for us to tune down the fan speed too much, at least give us the option to set it down to 20% with the Fan Curve option because this 20% is the Acer's factory default and it is already running fine at the moment if we select the "Automatic" option.

**Comment by abrfilho** [comment]
> The issue isn't quite fixed for me. Setting Fan Speed Control to Automatic in ARC Control keeps the fans at 30% minimum, which is louder than it was previously at idle with custom fan curve settings. Manually adjusting the fan curve gives the same results or worse now.
> 
> ![image](https://user-images.githubusercontent.com/134095787/267841957-1155a285-a489-4643-a7c9-dd2afe2a3553.png) These settings make the fans pulse every 3-5 seconds with the GPU at 46 degrees. Before 4644, the fans were capable of idling between 0 and 30%, which is still not possible with today's update.
> 
> ![image](https://user-images.githubusercontent.com/134095787/267842371-f104be22-5c5f-4c8a-9139-3f39606ba727.png) These settings pulse the fans about every 10 seconds, with the GPU around 55 degrees. As stated previously, before 4644 these settings would allow the fans to run slower, and therefore quieter, while keeping the GPU around 50 degrees.
> 
> If we were able to set the fan curve nodes to a percentage between 0 and 30, this might not be a problem at all. It seems arbitrary to disable control below 30%.



> Only partly fixed.
> 
> The "Automatic" option is fixed as it now operates in the same way as the original stock firmware, idle fan speed running around 1200 RPM (fluctuating 10xx~13xx, which is the same behavior as original).
> 
> Fan behavior below 20% in "Fan Curve" option has not been fixed. I am pretty sure with the original stock firmware and certain older versions of Arc Control, the actual fan speed could be configured and running at several hundreds RPM stable, which was the setting I used to use, similar to this one posted by [fjamesprice](https://github.com/fjamesprice):
> 
> > ![image](https://user-images.githubusercontent.com/134095787/267841957-1155a285-a489-4643-a7c9-dd2afe2a3553.png)
> > These settings make the fans pulse every 3-5 seconds with the GPU at 46 degrees.
> 
> Ever since certain version of Arc Control (I can't confirm exactly which version but I guess it was driver 101.4575), fan behavior started to be unable to stablize below 20%, ramping up and down (to 0 RPM). I didn't report the issue at that time because I chose to bear with it and adjusted my fan curve to stay all the way on the 30% line from 25°C to 55°C (or at least the "Automatic" option still worked, even though I didn't use it) so that the fan didn't ramp up and down. However, I did post a feature request in the Arc customer support forum that the Fan Curve option in the Arc Control should allow configuration down to 20% instead of 30% because the noise level when it ran around 1500 RPM (30%) was quite noticeably higher.
> 
> It was the driver update 101.4644 (with the firmware 20.1064.0) that made it worse (fan behavior just couldn't even stablize at 30%) and thus triggered many people to report the issue (fan speed ramping up and down) here.
> 
> Hopefully this issue can get further fixes. Ideally, the fan should be able to work at least down to 15% or even 10% because it indeed used to be able to do that and I had been experiencing that for many months until certain version of Arc Control changed it. Alternatively, if intel devs don't think it is safe for us to tune down the fan speed too much, at least give us the option to set it down to 20% with the Fan Curve option because this 20% is the Acer's factory default and it is already running fine at the moment if we select the "Automatic" option.

I asked on my last reply about the 30% minimum fan limit.

You can try import the fan curve from Predator Bifrost app.

<img width="479" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/54344422/4366f0f4-1b35-45ec-92f3-5d098cef3400">

To do that, you have to disable the option to apply tuning settings at startup
1 - Disable the option to apply tuning options at startup.
2 - Fully close Arc Control.
3 - Open Acer Predator Bifrost app
4 - Apply any profile (Silent and Normal have the same fan curve as my image, Turbo have a more aggressive at higher temperatures)
5 - Open Arc Control and the fan curve should be there

But even doing that, you can't set the fan to behave below 30%, but if you don't mess with the fan curve at this region, the usage will keep as shown in the image.

**Comment by Susie1818** [comment]
> You can try import the fan curve from Predator Bifrost app.

Thank you for the tip, but unfortunately the BiFrost app just doesn't launch at all with my PC, and so far I still can't figure out why.

**Comment by Karen-Intel** [comment]
Hi all! Okay, thank you for your feedback. Allow me to do some internal research as of why we have the 30% fan curve limitation in ARC Control (which summarizing your comments is the common problem) Now about the noise and the ramping, what's your feedback there? Just trying to focus on the original issue statement :) Ty

Karen

**Comment by abrfilho** [comment]
> Hi all! Okay, thank you for your feedback. Allow me to do some internal research as of why we have the 30% fan curve limitation in ARC Control (which summarizing your comments is the common problem) Now about the noise and the ramping, what's your feedback there? Just trying to focus on the original issue statement :) Ty
> 
> Karen

Regarding the main issue, it's now working as intended, I can say that for sure because my idle temperature increased a little, indicating that the fan is stable working at lower speeds.
Just to reinforce, the fan curve from Acer starts at 20%, as shown in the image below, before, to prevent the ramping up, I had to set the start at 34%.

https://user-images.githubusercontent.com/54344422/267984289-4366f0f4-1b35-45ec-92f3-5d098cef3400.png

**Comment by Darklegion1978** [comment]
My Feedback with the new Driver and FW.

If u use the Automatic Mode all is fine no ramping Up seen.
But when you use the Fan Curve, especially the import from the Bifrost Utility with the 20%, Fan is Ramping Up and down between 0 and 1550 Rpm,......

So nothing Changed with the Fan Curve and Ramping Up at me.

Greetings

**Comment by Susie1818** [comment]
> Just trying to focus on the original issue statement :)

The main issue caused by driver update 4644 (firmware 20.1064.0): fan speed could not stablize even at 30%; had to manually set fan curve to at least 33%, otherwise it would keep ramping down to 0 RPM every 5 seconds or so. However, 33% is translated to around 1600 RPM, and it is inevitably noisier than 30%(~1500 RPM). Of course the "Automatic" option was also broken because it is about 20% fan speed (~1200 RPM) at idle temperature.

With driver update 4824 (and a revised firmware 20.1064.0 flash for Acer A770): 30% fan speed is fixed, and the "Automatic" option is also fixed (which means 20% fan speed is good to go). In this regard, this fix has done its job.

======
Nevertheless, the problem regarding Acer Predator BiFrost's fan speed has not been completely fixed. The problem actually took place before the driver 4644. I don't remember which version of driver/Arc Control started to have the problem, though. The problem was that the fan could no longer operate stably below 20% if I set the fan curve at 0% for 40°C and 30% for 55°C. It would start ramping up and down (to 0 RPM) every few seconds, just like the symptom everybody was reporting about the driver 4644. Fact is that I had been using this setting (0% for 40°C and 30% for 55°C) without any problem for many months until certain version (I forgot which) of driver/Arc Control update, and during the time when it was okay, the fan speed maintained around several hundreds RPM (stable without dropping to 0 RPM) at idle temperature around 4x °C.

I understand that operating a PWM fan at too low PWM percentage is not good, and I think that's why Acer's factory default setting made its start point at 20%. Also, I have used quite a lot of PC motherboards, and I have seen most of their BIOS have PWM fans (chassis fan, CPU fan, etc.) start at 20%. Therefore, I suggest future versions of Arc Control should have the same design and let the fan speed limit line posited at 20% instead of 30%, and also make it jump vertically from 0% to 20% rather than climbing a slope from 0% to 20%.

Actually, if I remember correctly, a very early version of Arc Control bundled with driver version 4090 didn't have the 30% limit, and I could easily set the fan speed down to 10% without any problem.

**Comment by Darklegion1978** [comment]
But i seen another thing, Cpu-Z is showing now a Higher GPU Clock ❤️ 
We come closer to the real Speed of the Card ;)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123353653/cdf2b51c-e83e-4901-8401-2c2d79c9e8f4)

**Comment by Susie1818** [comment]
> Gpu-Z is showing now a Higher GPU Clock

This is not from the driver update. It's a new feature of the GPU-Z v2.55. It is stated in the [version history](https://www.techpowerup.com/download/techpowerup-gpu-z/#changes-v2-55-0) :

"Intel Arc GPUs now report the overclocked frequency (when active)"

**Comment by Karen-Intel** [comment]
Ty so much for your comments and quick feedback!
Our drivers and ARC Control is having several updates so we may have more improvements soon, we will not close this thread, allow me to share all this information in our internal report and I will get back as soon as I have any news
Really appreciate all your help and efforts!

Karen

**Comment by abrfilho** [comment]
I reported before that the issue was solved, but after I installed some fans in my case, and now getting a better air flow maintaining lower temperatures, the problem appeared again but in a lower scale than before.

Using the Automatic fan behavior from Arc Control, the fan will sometimes ramp up a little and go back, and using the fan configuration from Acer Predator Bifrost app will make the fan go to 0% just like before the correction.

**Comment by Susie1818** [comment]
So it means 20% is still not really stable. I thought it were stable probably because the actual GPU temperature has not gone bown to a point for exactly 20% PWM fan operation, I guess.

**Comment by Felipe-Intel** [comment]
FW update provided in driver 31.0.101.4824 fixed an issue with the behavior of the card's fans. 
 
Cards from different manufacturers have different sensitivity responses to temperature increase. Sometimes the idle state temperature can rise fast with a not so demanding workload and be brought back down by the rapid effect of the fans, resulting in what looks like an intermittent operation of the fans. 
 
Additionally, there is a limit to the minimum allowable PWM signal sent to the fans, and low PWM percentages will be clipped to the minimum PWM value. 
 
To avoid this situation you can either increase the threshold temperature or discard the 0 RPM mode by having the minimum RPM set to a value more than 20%.
 
If you have further questions regarding this specific GPU model's thermal solution design, please contact Acer Customer Support.

**Comment by Susie1818** [comment]
@Felipe-Intel I want to set the fan curve with the minimum PWM percentage to 20% but currently the Arc Control doesn't allow the anything below 30% except for 0%. I have already mentioned above long ago that Arc Control should start the fan speed threshold line at 20% rather than 30%, but you guys just wouldn't implement this into the Arc Control. I don't know why.

**Comment by abrfilho** [comment]
> FW update provided in driver 31.0.101.4824 fixed an issue with the behavior of the card's fans.
> 
> Cards from different manufacturers have different sensitivity responses to temperature increase. Sometimes the idle state temperature can rise fast with a not so demanding workload and be brought back down by the rapid effect of the fans, resulting in what looks like an intermittent operation of the fans.
> 
> Additionally, there is a limit to the minimum allowable PWM signal sent to the fans, and low PWM percentages will be clipped to the minimum PWM value.
> 
> To avoid this situation you can either increase the threshold temperature or discard the 0 RPM mode by having the minimum RPM set to a value more than 20%.
> 
> If you have further questions regarding this specific GPU model's thermal solution design, please contact Acer Customer Support.

Within Arc Control we can only set to a value equal or more than 30%, within Predator Bifrost App we can set a flat value equal or above 20%, but doing that the fan behaves as before the update, going to 0 then ramping up again, this behavior only started with the update 1064 and persists even with driver 4824 fix but at a minor scale.
Isn't possible to revert Acer's specific fan behavior part to the same as before the 1064 firmware?

**Comment by Susie1818** [comment]
I just did an experiment. I modified the file "C:\Program Files\Intel\Intel Arc Control\resource\js\pages\performance\performance_tuning.js" so that I can set the fan speed below 30% with the Fan Curve setting in the Arc Control. However, when I set it to 29% or anything below, the fan just slowed down to 0 RPM and then stopped without ramping up anymore. Then when I set it back to 30%, the fan went back normal spinning around 1500 RPM. And, if I choose the "Automatic" option, the fan can spin around 1100 RPM stably without ramping up and down. 

This experiment suggested that the Arc Control is doing something deliberately to interfere the fan speed. It doesn't simply pass the PWM percentage specified by the user to the hardware but rather forces a 0% signal whenever the percentage set by the user is equal to or less than 29%.

**Comment by Valkill27** [comment]
Hello to all sufferers, I can't say it any other way. 

I liked the performance of the card very much. But. 

I had an Acer Predator BiFrost Arc A770 OC 
As you all have already written, this is what was happening for me as well. I took the card back to the store because I thought that I had taken a system with more successful cooling on the Sparkle Titan I would get my claimed 0db mode...... 

But now I have the first day with Sparkle Titan A770, after a couple of hours of work it turned out that this card has 1 in 1 the same behavior as Acer Predator BiFrost, so the question is not in Acer guys, the question is in Intel..... 

And in addition to this. Intel says you can't use Intel Control on older PCs? 
I have a X99 from China with a Xeon e5-2680v4 (Broadwell) processor now by fate 
And everything installed smoothly with a simple windows registry fix.
 
And guess what works? Everything except the normal working fan and like all those who wrote here my fan grows up to 30% and drops and so a dozen second times a minute. Incredibly annoying even though I don't want to return this card. 

The bottom line is Intel are either assholes who just want you to buy a new CPU, or assholes doing the same thing who broke their own system and now the fans are constantly restarting.

I'm sorry that despite Intel's success with this card (I took it for Blender) and features, it makes noise when it doesn't make any sense. 0-30% and it's not a turbine fan like Acer....

**Comment by abrfilho** [comment]
> I just did an experiment. I modified the file "C:\Program Files\Intel\Intel Arc Control\resource\js\pages\performance\performance_tuning.js" so that I can set the fan speed below 30% with the Fan Curve setting in the Arc Control. However, when I set it to 29% or anything below, the fan just slowed down to 0 RPM and then just stopped there without ramping up anymore. Then when I set it back to 30%, the fan went back normal spinning around 1500 RPM. And, if I choose the "Automatic" option, the fan can spin around 1100 RPM stably without ramping up and down.
> 
> This experiment suggested that the Arc Control is doing something deliberately to interfere with the fan speed. It doesn't simply pass the PWM percentage specified by the user to the hardware but rather forces a 0% signal whenever the percentage set by the user is equal to or less than 29%.
> 
> I am using driver version 4826, by the way.
> 
> I must emphasize again that before driver update 4091, I could use the Arc Control Fan Curve setting to make the fan on my Acer BiFrost to revolve down to around 500 RPM stably without ramping up and down. I hope you guys at intel can communicate with Acer's engineers and figure out why it became like this as well as how to make the fan work in the way it used to be able to.
> 
> I don't understand why you guys had to modify the fan control part in the firmware when the driver update 4644 was out in the first place.

I tried the same here, any value below 30% goes to 0%, probably the controller is in another file.

The weird thing is, using Predator Bifrost I can put the fan below 30% without a problem, but I can't make a fan curve, only flat. Below 23% here, the fan goes to zero then up, at 23% the fan oscilates between 1066~1123RPM, same value as Intel Automatic configuration at idle, but using the Automatic configuration from Intel is not worth here when the card is under load, depending of the game, the temperature goes to 80+ easily and to me, makes no sense having to change it when I'm not putting some load on the card just to have less noise or less temperature under load.

**Comment by Susie1818** [comment]
To intel engineers:

Fan control is a very important quality of life feature for any GPU on the market, and right now after the intel driver update 4644, all Nvidia and AMD GPUs have this feature become much better than Arc GPU. It is not because either Nvidia or AMD improved their products. It is because you guys at intel messed up with the firmware and the Arc Control software and thus literally ruined it on our Arc GPUs. It's your fault because it's you that modified the firmware and the Arc Control software and resulted in these bugs.

Why on earth you guys are now telling me that it's not your responsibility to fix it and we customers should go contact Acer Customer Support? What the @#$*!!

**Comment by Valkill27** [comment]
> To intel engineers:
> 
> Fan control is a very important quality of life feature for any GPU on the market, and right now after the intel driver update 4644, all Nvidia and AMD GPUs have this feature become much better than Arc GPU. It is not because either Nvidia or AMD improved their products. It is because you guys at intel messed up with the firmware and the Arc Control software and thus literally ruined it on our Arc GPUs. It's your fault because it's you that modified the firmware and the Arc Control software and resulted in these bugs.
> 
> Why on earth you guys are now telling me that it's not your responsibility to fix it and we customers should go contact Acer Customer Support? What the @#$*!!

I try Acer BiFrost A770 and Sparkle Titan A770 , result is same

**Comment by Valkill27** [comment]
> To intel engineers:
> 
> Fan control is a very important quality of life feature for any GPU on the market, and right now after the intel driver update 4644, all Nvidia and AMD GPUs have this feature become much better than Arc GPU. It is not because either Nvidia or AMD improved their products. It is because you guys at intel messed up with the firmware and the Arc Control software and thus literally ruined it on our Arc GPUs. It's your fault because it's you that modified the firmware and the Arc Control software and resulted in these bugs.
> 
> Why on earth you guys are now telling me that it's not your responsibility to fix it and we customers should go contact Acer Customer Support? What the @#$*!!

So the questions are 200% not vendor specific

**Comment by Susie1818** [comment]
@abrfilho 
> modify the file to allow putting a value below 30%, with Arc Control closed, open Predator Bifrost and select any profile, then open Arc Control, select fan curve and try editing the fan curve with the values below 30% to see if it keep getting stuck at 0.

The Predator BiFrost app just cannot be opened on my Windows, and I can't figure out the reason why.

**Comment by abrfilho** [comment]
https://www.acer.com/us-en/support/product-support/APBF-IA770-16G-OC/downloads?suggest=apbf;1

I don't know if this can help with the Acer card problem, but inside the support page for Acer's A770 there's a driver version with firmware and OPROM files with different versions from earlier Intel drivers as checked by me comparing to a firmware compilation present in TechPowerUp forum (https://www.techpowerup.com/forums/threads/intel-arc-firmware-compilation-matrix.312440/)

**Comment by Susie1818** [comment]
I don't know how to flash the firmware(VBIOS) myself, and even if I do, every time when a new driver update is released from intel it is still going to overwrite the VBIOS on my A770 with their "new" firmware. It's like I just can't enjoy the benefit of latest driver updates with peace of mind.

**Comment by Susie1818** [comment]
@abrfilho 
Thank you for your expeiments and your findings.
Actually I think either 500~600RPM or 900~1000RPM is okay with me. The problem is right now the Arc Control only allows at least 30% PWM fan speed and it translates to 1400~1500RPM, which is unnecessary and too noisy when the GPU is idle.

If I select the "Automatic" option for the fan speed control, it does slow down to around 1100RPM when idle but it's responsiveness when the GPU is under load is too slow resulting in high core temperature, which I must use a customized fan curve to deal with.

**Comment by abrfilho** [comment]
@Susie1818 it's easy and quick to do, the only problem is the same when flashing FW, power loss... It's impossible to flash a firmware for another card and you can mismatch files version (there's four types of files: fw, fwdata, oprom_c and oprom_d), there's no problem with that.

With the older fw it's waaay quieter, I didn't test much to see the behavior in long term, if the low RPM have some problems, but noisewise, it's another world.

**Comment by vitduck** [comment]
Hi @abrfilho

I hope you don't mind some clarification regarding flashing the Bifrost's firmware. 
The step is as follow: 

1. Update to latest Intel driver, including the Control Center. 
2. Download the older driver provided by Acer, i.e. 31.0.101.3962 and extract the vbios from it. 
3. Flash the Bifrost with vbios obtained from (2) using the tool provided by TechPowerUp
4. Either set the min fan speed at 20% or import the fan curve from Acer Fan Control 

There can be issue with reported fan speed as you mentioned, probably due to strong coupling between driver and vbios. 
Is my understanding of the procedure correct ?

Hi @Karen-Intel 
The Bifrost lacks support for low idle power. So even at idle, the card runs a little warm, 
And a minimum fan speed of 30% causes unnecessary fan noise  
I understand that this is the responsibility of AIB, which is Acer in this case. 
However, if your team can already override Acer's 20% limit, could you consider unlocking the fan curve completely for us ? 

The min threshold for the fan to spin will vary from card to card. 
For instance, my 3060Ti accepts as low as 40%, corresponding to ~ 700 RPM. 
If I want Zero RPM, I just set it to < 40%. Or I can also leave it 50% for idle in summer. 

I can deal with high idle power consumption, but fan control is a crucial part of user experience. 
At this stage, Intel's fan control still lacks many features such as hysteresis, and response time. 
But I think first and foremost, it should allow user to control their hardware's the way they want.  

Thanks.

**Comment by abrfilho** [comment]
> Hi @abrfilho
> 
> I hope you don't mind some clarification regarding flashing the Bifrost's firmware. The step is as follow:
> 
> 1. Update to latest Intel driver, including the Control Center.
> 2. Download the older driver provided by Acer, i.e. 31.0.101.3962 and extract the vbios from it.
> 3. Flash the Bifrost with vbios obtained from (2) using the tool provided by TechPowerUp
> 4. Either set the min fan speed at 20% or import the fan curve from Acer Fan Control
> 
> There can be issue with reported fan speed as you mentioned, probably due to strong coupling between driver and vbios. Is my understanding of the procedure correct ?
> 
> Hi @Karen-Intel The Bifrost lacks support for low idle power. So even at idle, the card runs a little warm, And a minimum fan speed of 30% causes unnecessary fan noise I understand that this is the responsibility of AIB, which is Acer in this case. However, if your team can already override Acer's 20% limit, could you consider unlocking the fan curve completely for us ?
> 
> The min threshold for the fan to spin will vary from card to card. For instance, my 3060Ti accepts as low as 40%, corresponding to ~ 700 RPM. If I want Zero RPM, I just set it to < 40%. Or I can also leave it 50% for idle in summer.
> 
> I can deal with high idle power consumption, but fan control is a crucial part of user experience. At this stage, Intel's fan control still lacks many features such as hysteresis, and response time. But I think first and foremost, it should allow user to control their hardware's the way they want.
> 
> Thanks.

Yes, the steps are correct.
With the old vBIOS, the fan will work below 1000 RPM, using the new vBIOS, the fan goes to 0 if the RPM goes to any value below 1000 RPM.
Using Arc Control Automatic setting, the card will reach a value around 1000 RPM, using 30%, the minimum, the card will work at ~1400 RPM, and with Predator Bifrost with values below 30%, the card will go to 0 RPM, the only difference is that if the value is close to 20%, the fan will throttle more often.
I didn't test the old vBIOS too much here, didn't see how it behaves under load.
Don't know if this behave is related only to conflict between vBIOS and driver or if the OPROM file is involved too, since we don't have an older OPROM_D to test.

**Comment by vitduck** [comment]
@abrfilho 
Thanks for clarification and sorry for belated follow up. 
The Bifrost was loaned to me for a few days, so I am somewhat reluctant to flash the bios. 
Without a way to opt out of firmware update, it would be cumbersome due to high cadence of driver release.  

Since I  could not find specs for the Power Logic fan, i.e. PLA09215B12H, I don't know what the minimum allowed RPM is. 
But I have seen them in EVGA's Pascal series in which it could comfortably spins below 1000 RPM. 

The card has raw potential, but is currently held back by questionable design choices on software side. 
Lets hope BattleMage can sort out these issues including high idle power.

**Comment by abrfilho** [comment]
> @abrfilho Thanks for clarification and sorry for belated follow up. The Bifrost was loaned to me for a few days, so I am somewhat reluctant to flash the bios. Without a way to opt out of firmware update, it would be cumbersome due to high cadence of driver release.
> 
> Since I could not find specs for the Power Logic fan, i.e. PLA09215B12H, I don't know what the minimum allowed RPM is. But I have seen them in EVGA's Pascal series in which it could comfortably spins below 1000 RPM.
> 
> The card has raw potential, but is currently held back by questionable design choices on software side. Lets hope BattleMage can sort out these issues including high idle power.

Before the driver 4644 the card would go below 1000RPM without a problem.
Regarding the firmware updates, to prevent you can extract the exe driver installer and delete de folders FW, FWDATA and OPROM.

**Comment by vitduck** [comment]
In case some users would like to flash the Bifrost with previous version of the bios, the following files are required: 
- Flashing utility: https://github.com/Solaris17/ARC-Firmware-Tool 
- Firmware: https://github.com/Solaris17/Arc-Firmware/blob/master/101.3962/dg2_gfx_fwupdate_SOC1.bin 
- Firmware code: https://github.com/Solaris17/Arc-Firmware/blob/master/101.3962/dg2_c_oprom.rom
- Firmware data: https://github.com/Solaris17/Arc-Firmware/blob/master/101.3962/fwdata.zip
(The instruction is straightforward and can be found in the original repo)

@abrfilho 
I was finally able to flash the bios following your suggestion. 
Indeed the old fan curve was stable below 30% using Predator control center. 
Unfortunately I also observe oddity with fan speed: 

![FW_3324](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/44f943dd-0ce9-436e-b3dc-6a5b53f82dcb)

During booting or waking up from sleep, the fan will cycle several times and ramp up at full speed before coming down. 
Is this the old behavior of the card ? 

Nevertheless the new bios had fixed this issue and deliver better gaming performance as there are much less stuttering. 

Also, do you observe discrepancy between fan speed reported by Predator app and Intel app ? 
![RPM_30](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/a27c84ba-fc33-4082-aab8-57f70698d4e8)
 
In the picture above, the fan speed is set at 30% in Intel app, but Predator reports 35% instead 
This difference exists on the whole fan spectrum. At idle, the difference is noticeable. 
- Old vbios: ~ 900 RPM 
- New vbios: ~1200 RPM 
Since Acer has stopped updating their app, I hope we can lower the lower limit to 20% in future update.

**Comment by Susie1818** [comment]
@vitduck 

Thank you for all these efforts you put into testing with these different firmware.

> 
> I was finally able to flash the bios following your suggestion. Indeed the old fan curve was stable below 30% using Predator control center. Unfortunately I also observe oddity with fan speed:
> During booting or waking up from sleep, the fan will cycle several times and ramp up at full speed before coming down. Is this the old behavior of the card ?

Yes, I think so if I recall correctly.
 
> Nevertheless the new bios had fixed this issue and deliver better gaming performance as there are much less stuttering.

Thank you for these findings. Perhaps these are exactly the benefits of the new VBIOS. 

> * Old vbios: ~ 900 RPM
> * New vbios: ~1200 RPM
>   Since Acer has stopped updating their app, I hope we can lower the lower limit to 20% in future update.

Also a meaningful finding. Unfortunately the Predator app doesn't even launch with my Windows. I just hope that intel will fix the VBIOS for the Predator BiFrost soon.

**Comment by vitduck** [comment]
@Susie1818 
Thanks for confirming the original behavior of the old bios. 

> Also a meaningful finding. Unfortunately the Predator app doesn't even launch with my Windows. I just hope that intel will fix the VBIOS for the Predator BiFrost soon.

Regarding the Bifrost App: 
- The only solution I can suggest is to install Microsoft Visual C++ AIO (if you have not).
- I did try to reach out to Acer support to request software update since I don't want to run both Bifrost App and Arc Control for RBG control, and fan control, respectively. But acer support seems to be non-existent. 
- The Bifrost App lacks `GPU Performance Boost`  so we cannot undervolt, but the card seems to boost well with just 175W. 

IMHO, shipping the bios with driver installation is bad idea. 
Please let the AIB handle their own bios, so that they can implement an on-board bios switch if desirable.

**Comment by Susie1818** [comment]
@vitduck 

Actually I don't really care about the Predator app because the RGB has little to do with my build, which has a non-transparent side panel. And even if my case has a transparent side panel, I think BiFrost's default rainbow color theme is good enough for me and I don't have to adjust it.

On the contrary, all the features in the performance tuning tab of the Arc Control are relevant to my daily use. In fact I have never used the Predator app since day one of my BiFrost.

**Comment by Susie1818** [comment]
Hi @Karen-Intel,  

Long time no see! I just want to let you know about my new findings regarding this issue. I just bought a new intel reference design "Arc A750 Limited Edition" few days ago. Ironically, now I know how it does with its cooler fans. With the A750 LE, if I select "Fan Curve" and let the cooler fans to operate at 30% RPM for idle temperature, they spin at roughly 1300 RPM when the GPU is idle. On the other hand, if I select "Automatic" for the Fan Control in the Arc Control app, it is designed to enter zero-RPM mode when the core temperature is 45°C or below, but before the fans actually stop, they turn out to keep spinning way below 30% PWM, even down to a two-digit RPM at 46°C. This behavior is shockingly different from what we saw on the Acer BiFrost, whose cooler fans just instantly drop to zero RPM at 29% PWM (with the current new firmware). 

That being said, with the A750 LE at hand, I can practically set the fan curve with 0% at 25°C and 30% at 40°C in the Arc Control app, and it actually reaches an equilibrium around 1100 RPM between 36°C and 37°C. This is actaully very close to what I very much hope to have with my Acer BiFrost. (I used to have it balanced around 900-1000 RPM at idle temperature with the Acer factory firmware.)

**Comment by vitduck** [comment]
> That being said, with the A750 LE at hand, I can practically set the fan curve with 0% at 25°C and 30% at 40°C in the Arc Control app, and it actually reaches an equilibrium around 1100 RPM between 36°C and 37°C. This is actaully very close to what I very much hope to have with my Acer BiFrost

@Susie1818 
I also hope for ~ 1000 rpm at idle as well. It seems that Intel LE has the best features: fan, rgb control and ASPM. 

May I ask a quick side question, why do you overvolt the GPU with 25 mV ? 
As I understand from Intel official overclocking video, this is required when the power limit is raised. 
Here, you have truncated the F/V curve at 175W, so the voltage offset should be ineffective in this case. 
Thanks.

**Comment by vitduck** [comment]
@Susie1818 

Thanks for giving detailed explanation. 
I am able to stabilize OC boost clock by raising the voltage offset as you suggested.

**Comment by Susie1818** [comment]
@Karen-Intel 

Take a look:

![Screenshot (3)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/124469949/cdc646b1-c8b7-479c-b380-e5faf7458de1)

Idle temperature and fan speed are really low on my new Arc A750. The intel Arc Limited Edition allows fan PWM percentage to go as low as possible. This used to be feasible on my Acer Predator BiFrost A770 as well. Hopefully you guys can figure out how to bring it back ASAP.

**Comment by freak2fast4u** [comment]
@vitduck : thanks a ton for sharing this procedure !! I was able to downgrade back to vbios 1064 thanks to this, my problems with the GPU crashing upon rebooting into linux have disappeared ! (I triple boot with windows 10, Linux Mint and Manjaro depending on what mood I'm, and I use rEFInd for that).  

On VBIOS 1068, rebooting back and forth from windows to linux would almost systematically crash the GPU, with artifacts all over the screen and an unusable DE. On VBIOS 1064, I can reboot from linux to windows and vice-versa without any issues. So VBIOS 1068 is definitely broken to some degree. I had tried many different linux kernels and mesa versions without any success, but downgrading the VBIOS is the only thing that worked for me !

Sure, my problem wasn't with the fans, but I'll definitely be ripping out any VBIOS updates from every new driver I install until the issue is addressed. I will be reporting this in a separate ticket. Note that on VBIOS 1068, doing a cold-boot would succeed 90% of the time, whereas a reset/reboot would only succeed 10% of the time. On VBIOS 1064, a cold-boot works 100% of the time and a reboot also works 100% of the time.

Also, sometimes the Arc-Firmware-Tool will report that flashing FW timed out after 300s in the logs. I always try to flash until I get a 100% without any errors, else I fear my GPU would be bricked on the next reboot. I don't know if this is a hardware or software bug, but definitely needs to be verified before closing Arc-Firmware-Tool and rebooting.

**Comment by vitduck** [comment]
Hi @freak2fast4u

Thanks for sharing your experiences with Linux.  

> Sure, my problem wasn't with the fans, but I'll definitely be ripping out any VBIOS updates from every new driver I install until the issue is addressed. 

Bifrost owners essentials get the short end of the stick. 
 - The original vbios do have irregularities with fan curve beyond 2000 rpm that Intel has managed to fix. 
 - The current vbios' automatic fan curve is not sufficient below 80C so the card constantly throttles in itx builds. 

In my experiences, removing the bios files from installers crashed the installer at the very end of installation (4953). 
So personally, I will not update any driver until the fan issue is fixed. 

> Also, sometimes the Arc-Firmware-Tool will report that flashing FW timed out after 300s in the logs. I always try to flash until I get a 100% without any errors, else I fear my GPU would be bricked on the next reboot. I don't know if this is a hardware or software bug, but definitely needs to be verified before closing Arc-Firmware-Tool and rebooting.

The tool is not officially endorsed by Intel. 
According to the developer, there are safeguard features built-in to prevent flashing the wrong files. 
But there can still be a small risk involved with this process. Please tread lightly.  

It is a shame that the arguably best variant of A770-the LE edition-is now discontinued.

**Comment by peace20021** [comment]
I just bought my Sparkle A770 Titan, and I'm experiencing the similar issues, trying changing on my fan curve only makes the fan ramps up less often, but it's still there.

**Comment by freak2fast4u** [comment]
@peace20021 : it could be an airflow issue, since the hot air is evacuated towards the top of the card (at least on an LE model, I don't know about AIB models), which is, in a standard case, right up against the left panel. I tapped a piece of baking paper to the GPU to curve the airflow upwards, where I have 3 fans extracting the hot air, and I've never had any temperature problems since. 

Pics of the jankiest setup I could come up with : 

![IMG_20240116_161947_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/5a9e5e73-9f9e-4a6f-979d-146eeba51120)
![IMG_20240116_162013](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/b40ccfc9-923c-4521-8344-aa5d7fa60fc9)
![IMG_20240116_162022](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/4a431975-e2b6-45d8-9d9d-cda8bb6a6503)
![IMG_20240116_162039](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/5d9c0e9f-0ab9-4033-acd1-5edc14e33394)

**Comment by Susie1818** [comment]
@peace20021 

First of all you should try and see if your Sparkle A770 supports ASPM or not. If you want zero-RPM mode for idle, ASPM is a must. If unfortunately your A770 doesn't support ASPM, while dissipating more than 30W at idle, it is impossible for the core temperature to stay cool, and thus you will have to have the fans always on even while the GPU is idle. If that's the case, then you need to try and see if your A770 accept fan PWM below 30% because this is exactly the issue that exists with the Acer BiFrost variant.

**Comment by vitduck** [comment]
@peace20021 

I would like to echo @Susie1818 in the post above. 
47W at idle with zero RPM is gonna get hot fast. 

30% PWM is the hard limit that also exists with RTX 3000 series, i.e the fan will stops between 0 and 30% PWM. 
Because PWM is not linear, most NVIDIA AIBs tune the fan curve for the card to run silently while aligning to  30% PWM limit. 

IMHO, the current issue is that Intel AIBs have diverge set of lower PWM bounds. 
For instance, the Bifrost uses a single axial Delta fan, so they allow as low as 20% to mitigate the noise at idle. 
The Sparkle has three fans, so I think it would be possible to run them at sub-1000 RPM range. 

Could you set fan curve to 30% and see the RPM readout ?

**Comment by peace20021** [comment]
> @peace20021
> 
> I would like to echo @Susie1818's suggestion in the post above. 47W at idle with zero RPM is gonna get hot fast.
> 
> 30% PWM is the hard limit that also exists with RTX 3000 series, i.e the fan will stops between 0 and 30% PWM. Because PWM is not linear, most NVIDIA AIBs tune the fan curve for the card to run silently while aligning to 30% PWM limit.
> 
> IMHO, the current issue is that Intel AIBs have diverge set of lower PWM bounds. For instance, the Bifrost uses a single axial Delta fan, so they allow as low as 20% to mitigate the noise at idle. The Sparkle has three fans, so I think it would be possible to run them at sub-1000 RPM range.
> 
> Could you set fan curve to 30% and see the RPM readout ?

I just read throught the specifications of the ARC 770 and figured it out. It turns out that ASPM mode can't kick in if there are more that the ASPM limitation allow which is 2 1080p 60Hz screen or 1 4k 60hz screen. I am running dual monitor with 1 1080p 60hz and 1 1080p 240hz.

**Comment by Felipe-Intel** [comment]
After further review, the teams involved reaffirmed that the fan curve was built to specifications with minimum 30% PWM as defined by product architecture requirements. This setting/configuration will not be changed as this will cause issues broadly for many more users with different fan configurations.
Also, well noted by @peace20021, "low power mode" is restricted to specific monitors/graphics settings. Anything different won´t let the card to enter a low power mode. More power draw means higher operation temperature that will affect fans behavior. Check [this article](https://www.intel.com/content/www/us/en/support/articles/000092564.html) for details on Arc Cards power consumption.

We'll proceed to close this bug report.

**Comment by Susie1818** [comment]
@Felipe-Intel 

I can't believe how brutal you are that you just closed this case without the consent from those who reported the issue and you just ignored all the discussion and information contributed by these people. All the evidences provided here have pointed out that you guys at intel messed up the firmware with the Acer Predator BiFrost variant. I don't know why you guys can be so irresponsible and just leave the problem unsolved. Also you are obviously talking nonsense because I have pointed out the fact that the intel A750 LE allows fan PWM down to probably 2%.

**Comment by Susie1818** [comment]
@EstebanIntel
@Karen-Intel 

This is terrible. I can't believe you guys handle the problem in this way.

**Comment by fjamesprice** [comment]
> After further review, the teams involved reaffirmed that the fan curve was built to specifications with minimum 30% PWM as defined by product architecture requirements. This setting/configuration will not be changed as this will cause issues broadly for many more users with different fan configurations. Also, well noted by @peace20021, "low power mode" is restricted to specific monitors/graphics settings. Anything different won´t let the card to enter a low power mode. More power draw means higher operation temperature that will affect fans behavior. Check [this article](https://www.intel.com/content/www/us/en/support/articles/000092564.html) for details on Arc Cards power consumption.
> 
> We'll proceed to close this bug report.

So is Intel going to buy my card back?  The bottom line is it wasn't this loud when I got it, and your team made it annoying to have in my computer for months while we waited for it to go back to normal.  The issue is not resolved.

**Comment by peace20021** [comment]
> Also, well noted by @peace20021, "low power mode" is restricted to specific monitors/graphics settings. Anything different won´t let the card to enter a low power mode. More power draw means higher operation temperature that will affect fans behavior.

This sounds stupid, but my RTX 3060Ti runs the same configuration at idle doesn't even load the fan at all. You guys need to figure it out at a lower power idle consumsion. I'm not even sure if this is Sparkle's fault for having bad cooler or Intel's fault for not being able to make the idle properly.

**Comment by vitduck** [comment]
Although the dice has been cast on this issue, I would like to set the record straight: 

1. The nature of the Bifrost's fan curve 
<img width="479" alt="Bifrost fan curve" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/95074611-1beb-42af-8ffd-95d93d1379c7">

- The above fan curve, which can be imported from Predator Control, allows a minimum of 20% PWM
- Instead of enforcing a 30% minimum as stated by Intel representative, Acer stipulated the maximum PWM for each profile, e.g. the 'Silent' profile has maximum PWM of 40% with axial fan and blower fan in synchronization. 
```
 <profile name="Silent"> 
    <PFMode>Silent</PFMode> 
    <CoreBoostClock>2400</CoreBoostClock> 
    <MEMBoostClock>1620</MEMBoostClock> 
    <GPUVoltageLimit>0.851</GPUVoltageLimit> 
    <PowerLimit>160</PowerLimit> 
    <TemperatureLimit>78</TemperatureLimit> 
    <TemperatureScale>Celsius</TemperatureScale> 
    <FanSpeedOption>Auto</FanSpeedOption> 
    <AeroBlade>40</AeroBlade> 
    <FrostBlade>40</FrostBlade> 
    <LinkSpeed>true</LinkSpeed> 
  </profile>
```
- Thus, the fan curve will be tapered toward 40%, 60% and 70% for Silent, Normal and Turbo, respectively.  
2. Discrepancy in Intel Arc Control

- With automatic control 
![Automatic](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/f408d1fc-55b7-44a5-8409-369d84da602f)

- With manual fan curve (30% minimum) 
![Fan curve](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/575950/4bb5f1b2-f98c-459d-aef7-07d54116c924)
- If 30% is the minimum PWM, how could one explain the fact that 'automatic' allows the fan to spin at 300 RPM lower ?
- The logical conclusion is that the Bifrost originally has no 30% limit which was only imposed approximately one year after the card was launched at the tail end of 2022. Since the blower and axial fans are synchronized, Acer would have tuned the curve down to mitigate noises at idle. This is now undone by Intel Arc Control. 

I would like to thank other users who have shared their data and voiced their opinion.
Perhaps it is time to move to a greener pasture.

**Comment by Jorn-T** [comment]
Same problem here, on a new B760 i5-13500 computer.  

Sparkle Titan ARC A770. Fans are spinning up and down every three to four seconds, extremely annoying, and will probably wear out the fans pretty fast, with 1000 start/stop cycles an hour when idling. 

I'm also getting a coil whine every two seconds or so, while at the same time, the card throttles the clock speed up and down. Coil whine is at full clock speed, no whine while throttled. BZZT-BZZZT-BZZZT.. With FPS in Fortnite alternating between 120-80-120-80.. Very strange behaviour for a brand new graphics card.

![2024-01-20 (12)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/157257901/e23017ca-d0de-41f7-960c-d61cba5c5829)
![2024-01-20 (10)](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/157257901/405d8417-1992-4e52-8dea-14343c41b331)

**Comment by Susie1818** [comment]
@Jorn-T 

> Sparkle Titan ARC A770. Fans are spinning up and down every three to four seconds, extremely annoying, and will probably wear out the fans pretty fast, with 1000 start/stop cycles an hour when idling.

If your "Fan Speed Control" is on the "Automatic" option, it is probably due to your GPU running very close to its zero-RPM threshold temperature. AFAIK my intel Arc A750 LE, if using the "Automatic" mode, is configured for zero-RPM at 45°C, and from your screenshots it looks like your A770 has similar configuration. A workaround is to set a customized fan curve and let the fans to be always on.

> I'm also getting a coil whine every two seconds or so, while at the same time, the card throttles the clock speed up and down. Coil whine is at full clock speed, no whine while throttled. BZZT-BZZZT-BZZZT.. With FPS in Fortnite alternating between 120-80-120-80.

You can try installing "Intel® Graphics Command Center (Beta)" from Microsoft Store and go to Preferences→Global Settings→Adaptive Sync and then switch "Adaptive Sync Plus (ASP)" ON.

**Comment by Jorn-T** [comment]
Setting a manual fan curve with fans always at 30% or above makes more noise, but does not prevent the fan from stopping roughly every 10 seconds. Something is definately wrong with the driver (or firmware).


________________________________

**Comment by ochompsky** [comment]
man this sucks, appears to be no workaround and no interest to fix this.  i got a new card and love the AV1 encoding but this noise is a dealbreaker.  return i guess?

**Comment by vitduck** [comment]
@ochompsky 

> man this sucks, appears to be no workaround and no interest to fix this. i got a new card and love the AV1 encoding but this noise is a dealbreaker. return i guess?

If you are talking about the Bifrost, then it is indeed the worst Arc. 
- Acer no longer updates the Bifrost App which has a RGB bug with iGPU. 
   Acer had never thought that the users would actually use Intel CPUs. 
- Intel also has swept the fan control bug under the rug. 

So: 

- If you want plug-and-play, just go with NVIDIA. 
- If you don't care about RT/FG, RX 7800XT offer similar VRAM bandwidth with a quite competent AV1 encoder. 

You can always earn back money, but  you cannot earn back the time spent trouble-shooting this card.

**Comment by Susie1818** [comment]
Intel's attitude is so arrogant and irresponsible. They broke it and didn't want to fix it and arbitrarily said the case was closed.

**Comment by ochompsky** [comment]
> @ochompsky
> 
> > man this sucks, appears to be no workaround and no interest to fix this. i got a new card and love the AV1 encoding but this noise is a dealbreaker. return i guess?
> 
> If you are talking about the Bifrost, then it is indeed the worst Arc.
> 
> * Acer no longer updates the Bifrost App which has a RGB bug with iGPU.
>   Acer had never thought that the users would actually use Intel CPUs.
> * Intel also has swept the fan control bug under the rug.
> 
> So:
> 
> * If you want plug-and-play, just go with NVIDIA.
> * If you don't care about RT/FG, RX 7800XT offer similar VRAM bandwidth with a quite competent AV1 encoder.
> 
> You can always earn back money, but you cannot earn back the time spent trouble-shooting this card.

it's not just bifrost cards, it's also happening on sparkle cards.  i am engaged with them to see if there's a firmware level way to handle this but either way, the fan is gonna last long with these spindowns and spinups

**Comment by ochompsky** [comment]
for those with a sparkle card, ive been in contact and they said they are shipping a new firmware but it will take up to 2 months to trickle down through intel

**Comment by trash-it** [comment]
Acer wants me to send my Bifrost, because the same fan problem. And also why zero fan mode will work only few minutes. But can't imagine, that it will change something. Because it's no problem with my specific card. Seems many Bifrost and Sparkle fans run wild.

**Comment by vitduck** [comment]
> Acer wants me to send my Bifrost, because the same fan problem. And also why zero fan mode will work only few minutes. But can't imagine, that it will change something. Because it's no problem with my specific card. Seems many Bifrost and Sparkle fans run wild.

@trash-it 

Could you let me know how you got hold of Acer customer support ? 
I couldn't find a user portal or email address anywhere to contact support. 

I have been trying to request them to fix the device enumeration routine in the Bifrost Control App. 
Beside fan curve issue, it doesn't play nice with iGPU so monitoring and rgb functions are tied to iGPU instead of A770.

**Comment by trash-it** [comment]
I reach the American Chat Here:
https://service.acer.com/chat/support/en/US/
Support even said, that the zero fan mode should also work. Which confused me, because I thought it's an hardware issue.

Anyway here I reached the rma service. But it's the German one.
https://customercare.acer-euro.com/customerselfservice/CaseBooking.aspx?CID=DE&LID=GER&OP=1
But here there wasnt any conversation. I wrote the problem with the zero fan mode and the noise fan rpm and next day I had the answer, that I have to send my card in. Which I will do tomorrow.

**Comment by vitduck** [comment]
> @vitduck I reach the American Chat Here: https://service.acer.com/chat/support/en/US/ Support even said, that the zero fan mode should also work. Which confused me, because I thought it's an hardware issue.
> 

Thanks. 

I concur on the noise issue. The bifrost is
- Louder than others at same temperature
- Hotter than others at same rpm 

At least the design is interesting (?!)

**Comment by Susie1818** [comment]
[A follow-up for those who are still interested](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/733)

**Comment by jj-uk** [comment]
@IGCIT 
The issue with fan speed being erratic, ramping up and down is a well known issue that affects all ARC A-series cards from A310-upwards.
 
There are many many reports on various websites; AI mentions it when asking for a description of the ARC A card; every review on vendor websites mention it.

I find it somewhat unbelievable that a company the size of Intel cannot write a simple control algorithm to control the speed of a fan based on the temperature of the card.

Seriously, PWM fan control has been a thing for 30+ years and Intel doesn't have an engineer that can write the software to do this simple control.

How embarrassing it must be for Intel - everyone's laughing at you and your ARC A-series graphics cards with ramp up / ramp down annoying fan control.

Setting a constant speed percent to less than 42% results in 0% to 40% on 10 secs, off 10 secs ramping cycles when the card is idle and at 40c.

Setting to 50% constant speed results in ramping from 50% to ~60% and back to 50% every 10 secs.  What are you doing?! Seriously, what are you doing!?!!


I'm returning my card for a refund.
