### ISSUE TITLE
Assassin's creed valhalla

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#45]
#### Game _[Required]_
Assassin's Creed  Valhalla 

---
#### CPU _[Required]_
I7 1165g7

---
#### GPU Driver Version _[Required]_
27.20.100.9316

---
#### Rendering API _[Required]_

**API** _[DirectX, OpenGL, Vulkan]_:
**API Version** _(example DirectX 12)_: 

directx 12
---
#### Windows Build Number _[Required]_
latest build 

---
#### Description _[Required]_
Game works but takes 5 minutes go start, 
In game there are lots of glitches happening and light bleeding 

---
#### Steps To Reproduce _[Required]_

Start the game and try to face a source of light 
---
#### Game graphics settings (screenshot or text) _[Optional]_ _[Recommended]_
1280*800p low settings 

---
#### Screenshots _[Optional]_

---
#### Save game _(if possible, could help solve the issue faster)_ _[Optional]_

---
#### Game custom logs (if available) _[Optional]_ _[Recommended]_

---

**Comment by mva94** [comment]
@leoben2 
Just as bad on latest drivers...

**Comment by leoben2** [comment]
We reproduced this and is in the debug/dev queue.

**Comment by mva94** [comment]
@leoben2 this is not solved on the latest drivers I don't why you stated so but it is just as bad and unplayable. 
Games takes no joke 5 minutes to boot .
You can only play with the camera aimed towards the flow as otherwise you get glitches or a completely white screen as observed in the second pic.
![20210528_151158](https://user-images.githubusercontent.com/78859716/119989361-60e5c480-bfc7-11eb-9ecc-49d9cd660081.jpg)
![20210528_151204](https://user-images.githubusercontent.com/78859716/119989369-63481e80-bfc7-11eb-998a-5607afb09b56.jpg)

**Comment by mva94** [comment]
@leoben2 you mentioned again in the latest beta that this game was solved. 
Here is the result of the ' solved drivers '  https://youtu.be/__T9Kp12E1I

The games still takes 10 minutes to get to the menu by the way

**Comment by the-minister** [comment]
Still facing this issue. When we try to face a light source, the game is unplayable. Everything becomes white. Only the health bar and the compass are visible. 
Details:
	Intel(R) Iris(R) Xe Graphics
	Driver version:	30.0.100.9684
	Driver date:	09-07-2021
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 0, device 2, function 0
Device: GPD Win 3
Would be grateful for a fix.

**Comment by PacoAvelar** [comment]
I just booted and played from New game up to grown up character on:
i7 1165G7
16 GB ram
Win 11
GPU Driver 9862
Screen resolution 720p,
In game settings to low


It does take a lot to boot : 
   - from start to intro screen ~5 minutes
    - checking for add ons +~1 minute
    - from main menu to in-game +~1 minute
   
   Total time from exe start to in game ~8 minutes

    @the-minister , @mva94 
     can you confirm that the graphical issues are gone ?

**Comment by estebanr863** [comment]
Hi @mva94! We are looking at the other reported issues (white screen when facing a light source and the long load time). However, I'll appreciate more info on the crash. Does it happen at launch or during gameplay?

**Comment by mva94** [comment]
@estebanr863 hey !
I'm already half way through the game, that's when I have it happening pretty much randomly, glitches happen a lot when your camera is facing towards the sun/sky

**Comment by estebanr863** [comment]
Hi @mva94, can you provide your save files so we can try and reproducing the issue?

**Comment by mva94** [comment]
@estebanr863 crashes are gone with the latest drivers, I've player two more hours today.
Only issue left is the light issue
