### ISSUE TITLE
Nier: Automata - Crash 

### ISSUE THREAD

**Issue by chibi4588** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#49]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Nier: Automata 
---
#### Processor / Processor Number [Required]
Intel Core i7-1160G7
---
#### GPU Driver Version [Required]
- [X] 30.0.100.9667 (*latest Beta driver*)
- [X] 27.20.100.9466 (*latest*)
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1.  Start the game
2. Begin game
3. Crashes wthin 5 minutes, while shooting very 1st mobs.  Display / Graphics crash, white screen remains while game is still running

---
#### Device / Platform [Optional][Recommended]
 OnePC One GX1 Pro

---
#### Game Settings [Optional][Recommended]
 Default settings

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---

**Comment by bcysewsk** [comment]
Sorry that you need to wait. We reproduced the issue and now we're analyzing what caused the problem

**Comment by bcysewsk** [comment]
Is it 100% reproducible or do you see it sometimes? Actually we have problem to reproduce it again for analysis. 
If it's 100% reproducible on your machine can you share crash dump? Here's how to do that:
https://www.windows10forums.com/articles/how-to-enable-minidump-logs-in-windows-10.50/
We would require full dump not a small dump as it's presented. *.dmp file should show after game crash in C:\Windows\Minidump or C:\Windows\LiveKernelReports

**Comment by chibi4588** [comment]
@bcysewsk 
It is 100% reproducible on my system everytime, however, it is not generating a crash dump when this happens in either of the directories you reference.

**Comment by Valkirie** [comment]
> @bcysewsk
> It is 100% reproducible on my system everytime, however, it is not generating a crash dump when this happens in either of the directories you reference.

Can you enable local crash dumps: https://helgeklein.com/blog/2018/10/creating-an-application-crash-dump/

**Comment by chibi4588** [comment]
I have created the registry key for WER, and it is still not generating a crash dump... perhaps because the game has not fully crashed?  Whitescreen while the game is still running.  Not sure.

**Comment by Valkirie** [comment]
> I have created the registry key for WER, and it is still not generating a crash dump... perhaps because the game has not fully crashed? Whitescreen while the game is still running. Not sure.

Well most likely drivers crashed but not the game.

**Comment by ihainan** [comment]
I met the same issue on GPD WIN 3 and ONEXPLAYER (both are i7-1165G7 and 9466 drivers), it's very strange that the issue only occurs when I play as 9s.

GPD WIN 3: https://youtu.be/Ao4_J4i7c7E?t=317

ONEXPLAYER: https://www.youtube.com/watch?v=ppvAtk099Vs

**Comment by ihainan** [comment]
It seems that the 9667 driver has fixed this issue? 

https://www.youtube.com/watch?v=Xyc61RewsvQ

**Comment by Valkirie** [comment]
Fixed indeed. Closing. Thanks for the notification !

**Comment by chibi4588** [comment]
Why was this closed? This bug was not fixed

**Comment by chibi4588** [comment]
On latest drivers, if I need to record to Youtube I can, this is not fixed just because a contributor says as much on my opened bug.  Please reopen

**Comment by chibi4588** [comment]
> Fixed indeed. Closing. Thanks for the notification !

@Valkirie Please dont hijack my bug with your squishy, lack of substance, just works answer. 
https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/49#issuecomment-858714292

Reopen as not fixed

**Comment by chibi4588** [comment]
Video of crash uploaded to Youtube showing crash, whitescreen, while game still running.
https://youtube.com/watch?v=ml6vn4LrYN4&feature=share

**Comment by PacoAvelar** [comment]
I just booted and played from New game up to the bunker (40 mins) on:
i7 1165G7
16 GB ram
Win 11
GPU Driver 9682
Screen resolution 720p, 
In game settings to low 

Steam version

@chibi4588 can you confirm that it is working ?

**Comment by Valkirie** [comment]
@chibi4588 any update ? Can you confirm it's fixed, or not ?

**Comment by chibi4588** [comment]
@Valkirie Apologies for the delayed reply.  I am out of country presently, without my unit to test.  I will reply once I am back home and update this bug.
Thanks for reaching out.

**Comment by chibi4588** [comment]
@Valkirie and @PacoAvelar 
As of the latest driver, 30.0.100.9864... this issue seems to have been resolved.  I would say we can go ahead and close out this bug #49.
Thank you both very much for your diligence, and continued support of the community.
--Chibi
