### ISSUE TITLE
Offroad textures not loading at all in NFS Heat

### ISSUE THREAD

**Issue by weebawop** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#510]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Need For Speed Heat

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [X] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-12500h

### Graphic Card [Required]

A370M

### GPU Driver Version [Required]

- [X] 31.0.101.4824
- [ ] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12619440/igcit_ssu.txt)

### Description and steps to reproduce [Required]

This is what the terrain should look like offroad
![g6vpllt3am371](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/694f0569-e31f-4b1e-913d-7b57e8b1ba8e)

and this is what it actually looks like. it's just smooth. no definition
![no terrain](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/46519780/22c6915c-a47f-4bce-b8b5-406b4b8362b9)

it isn't just an issue offroad but also on the side of the roads where the terrain should have small stones, instead it's just smooth. I already use DXVK on this game to fix a driver graphical glitch where the taillights and headlights don't look the way they should but DXVK doesn't fix the smooth terrain issue. For clarity, the smooth terrain is a problem with and without DXVK. Using high settings doesn't fix the issue

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

1920x1200

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Medium settings, 1920x1200, 90% resolution scale.

**Comment by BiZkViT96** [comment]
There are already two bug reports. #307 #392

**Comment by Karen-Intel** [comment]
Hi all, just leaving here the internal report number FYI: 14019323627

Karen

**Comment by jamesgecko** [comment]
I have smooth offroad terrain with DXVK. Without DXVK, offroad terrain is a reflective surface.

![20240621191003_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44252/015e49d5-a6c2-44c1-8861-3b5387bca55d)
![20240621191025_1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/44252/dd39df13-1a5b-497f-a086-aeeb883eb5bf)

**Comment by rmorera-intel** [comment]
Hi @weebawop this issue should be fixed with driver [32.0.101.6127 and newer](https://www.intel.com/content/www/us/en/download-center/home.html). 
Please give it a try and let me know your feedback.

**Comment by Xtr126** [comment]
Issue is still there with Arc 140V and latest driver 32.0.101.6987

**Comment by Arturo-Intel** [comment]
@Xtr126 Can you please open a new case? 

--r2
