### ISSUE TITLE
Cyberpunk 2077 has flatlined

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#6]
#### Game _[Required]_
Cyberpunk 2077

---
#### CPU _[Required]_
Intel(R) Core(TM) i5-1035G7

---
#### GPU Driver Version _[Required]_
Intel(R) Iris(R) Plus Graphics

---
#### Rendering API _[Required]_
**API** _[DirectX, OpenGL, Vulkan]_: DirectX
**API Version** _(example DirectX 12)_: 12

---
#### Windows Build Number _[Required]_
Windows 10 20H2

---
#### Description _[Required]_
Cyberpunk 2077 crash to desktop after a short period of time.

**Comment by Valkirie** [comment]
Intel is working on a fix. A few bug fixes were tested internally and we should expect progress for the next driver release by end of month.

**Comment by Valkirie** [comment]
![image](https://user-images.githubusercontent.com/934757/105321409-b51b0b00-5bc7-11eb-96eb-a2d3090fca64.png)
Game is reported working on fullscreen mode but is having crash issues while running Windowed. Still a huge achievement from Intel's team !

**Comment by leoben2** [comment]
With the latest intel.com driver, the front up crashing is fixed, however there's one occuring during gameplay. Working on that one now.

**Comment by leoben2** [comment]
This second part seems like we need to work with CDPR on. Will keep you posted.

**Comment by dissociativity** [comment]
That's Tiger Lake, the issue is stated for Ice Lake, which I believe still crashes, I'll need to transfer the game to my Ice Lake device to double check, but I'm fairly sure Ice Lake still has more issues in general than Tiger lake with DX12/Vulkan games.
Please don't leave Ice Lake behind.

**Comment by leoben2** [comment]
Can  you try the latest beta on Intel.com?

**Comment by nielo360** [comment]
Does not work on the win max ice lake on the latest beta driver crashes out after 4 mins after first time play. Then cannot be run again

**Comment by nielo360** [comment]
Does not work on ice lake win max even with latest driver crashes after a min in game. Why not support iris

**Comment by nielo360** [comment]
Crashes after 1 min on ice lake with 1.2 patch.. its actually playable until it crashes.

**Comment by Valkirie** [comment]
Closing this one. Cyberpunk no longer crashes but now has major glitches since latest drivers.
Please use #55 to follow-up.
