### ISSUE TITLE
Helldivers 2 looks dark and foggy

### ISSUE THREAD

**Issue by goldenx86** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#775]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Helldivers 2

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 1240P

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[intel.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15175014/intel.txt)

### Description and steps to reproduce [Required]

Join any planet, visibility won't go past 20-30 meters.
https://youtu.be/_V22W3hkeC4 
https://www.reddit.com/r/Helldivers/comments/1b0rfpy/helldrivers_2_on_intel_iris_xe/
Issue is widespread and reported by several players. Graphical settings or API in use are irrelevant.

Performance is also terrible.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/378827b6-ccdd-4c3a-8b9a-fd16faee57b4)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/ed29a1fa-20e1-4940-806c-7ec46268ac02)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/797564a2-15e3-4bd9-91a6-82be838c9a90)

### Device / Platform name

Asus Vivobook X1502ZA

**Comment by Adrian-Intel** [comment]
@goldenx86 thank you for sending this report. I will check on my end and will send my findings here.

**Comment by goldenx86** [comment]
Tested Linux too via Proton, issue happens with both the i915 and the Xe DRM drivers, so anv is affected also regardless of if D3D11 or D3D12 is in use.

**Comment by Adrian-Intel** [comment]
@goldenx86 I used the game settings you provided and here are some screenshots. Can you please confirm if these are similar to what you get?

![Iris Xe 1](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/498dcf8f-f8bb-48f8-b944-12c3f9e87b1c)

![Iris Xe 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/158005437/4d8f41e8-c648-47d1-ab75-2258c1a31a09)

**Comment by goldenx86** [comment]
Yes, that's the experience I get. Playable character, enemies, allies, and most of the environment are just always dark, even under direct light.
Feels like playing as a Jurassic Park dinosaur, you only see contrasts.

**Comment by goldenx86** [comment]
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/bfa00091-9917-4ef5-90bd-e294834c674a)
Same result with 5522.
Hope it's not just lack of FP64 support.

**Comment by Adrian-Intel** [comment]
@goldenx86 thank you for sending the sample screenshot with the latest 5522 driver. I checked on my end and can confirm that it still persists. There is already an open case with the debug team regarding this. I will send updates here once available.

**Comment by goldenx86** [comment]
Tested a snow map and it seems fixed in 5590. Will test more after I'm done with some IRL university tests.

**Comment by goldenx86** [comment]
Can confirm the issue persists with 5590, even in Windows 24H2.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/42481638/38f447a6-f2e8-4ae6-944a-7c7c09f413ec)

And even adds its own spin to it.

**Comment by Adrian-Intel** [comment]
@goldenx86 I checked on my end and the issue still persist with 101.5590 driver. I informed the debug team and still waiting for any feedback.

I do not encounter the white big dots you encounter with you last screenshot though.

Lastly, can you share the screenshot of the snow map that you said appears to be fixed? Also, what is the name of the map?

Thank you very much!

**Comment by goldenx86** [comment]
It was Vernen Wells, currently unavailable for playback.

**Comment by Adrian-Intel** [comment]
@goldenx86 There is already an existing bug report (18035939175) for this. For any updates, I will post here. Thank you very much!

**Comment by goldenx86** [comment]
Roger roger.

**Comment by Pjorus** [comment]
Its a problem with the intel iris xe...
Intel won't fix it, because "its below minimum system requirement" even though it runs pretty okay.
HD2 devs are aware of the issue, they just have a lot more things to work with, there arent many people on this "graphics card" and above all, its not completely their fault. So for the devs its not top priority, and intel wont fix it.
Welcome to the bullshit of intel...

**Comment by goldenx86** [comment]
I always assumed they were stalling for time until the official EoL announcement.
The day they learn to code drivers for the API first, AAA games second, they will start selling usable products.

**Comment by Pjorus** [comment]
Yeah, they are probably stalling...
Its sad, because the fps isn't even that bad, its just the visual that make me wanna puke...

**Comment by SavageWaffle** [comment]
Is this still an issue?

**Comment by goldenx86** [comment]
Nothing has improved for Gen 12.1/12.2 hardware, since 2022.

**Comment by goldenx86** [comment]
![Image](https://github.com/user-attachments/assets/9c46ab90-f83c-4849-8947-b4a2b5a3c9ba)
No improvements on 6559.

It's impresive how the only relevant Intel GPU on Steam Hardware Survey, this one, has zero driver development on all fronts. I wouldn't be surprised if the CPU overhead fix for Battlemage turns into a Celestial exclusive at this rate.

**Comment by goldenx86** [comment]
Yeah, any source of light you produce works, explosions too.
Wonder how happy the Iris Xe MAX owners are, getting the same treatment on a dedicated GPU that was also promised driver support.

**Comment by Pjorus** [comment]
Damnn, the dedicated GPU is also bugging out in hd2??!

**Comment by Adrian-Intel** [comment]
@goldenx86 

I apologize for the delay in providing updates. After thoroughly testing, we've found that Iris Xe did not meet the minimum requirements of the game and issue encountered is due to hardware limitations. With this, I will be closing this ticket. Thank you for your understanding and patience.

**Comment by EstebanIntel** [comment]
Hi @Pjorus,

Even when there are various games with issues that seem to be the same one, in the vast majority of cases the root cause of each issue is a different one. So, fixing an issue on one game almost never results on automatic fixes on other games. This is why issues and fixes need to be worked on a per-game basis. And a lot of times, these fixes require the collaboration between Intel and the game developer. Also, please understand that game developers set the minimum requirements for a reason. And in the vast majority of cases, they won't work with us to fix issues that are only affecting systems that don't meet their minimum specs.

If you are having issues on other games where your system does meet the game developer's minimum specs, please submit a ticket for and we will be happy to help.

**Comment by Pjorus** [comment]
Hi @EstebanIntel,

I fully understand that fixing this issue for one game does not automatically fix every other game. I also understand that game developers set minimum system requirements, as I am a game developer/software engineer myself.

However, there is a difference between not being able to help and not wanting to help.

I have been in contact with the Helldivers 2 development team multiple times, and they always tell me they have more important fixes that need attention, which I fully understand. When contacting Intel, they almost always dismiss the issue immediately as "below system requirements." If they don't do so right away, they do after experiencing the issue themselves and deciding it’s too much work—at which point they fall back on the "below system requirements" excuse again.

This GitHub thread was actually the first and only place where I saw people genuinely trying to investigate and resolve the issue. I just find it a little funny that what these big companies claim they "can’t" do (or rather, don’t want to do) can be accomplished by a few smart modders—just like it was for Helldivers 2.

Once again, I understand that fixing this issue won’t fix everything. I'm not even asking anyone to fix it right now—I’m simply asking for some genuine investment in your customers and community by improving the drivers for this GPU.

**Comment by goldenx86** [comment]
![Image](https://github.com/user-attachments/assets/cbcf5811-98af-4264-87f2-7a231fd17bc3)

> did not meet the minimum requirements

Why do you "officially" support an architecture you actively avoid maintaining. Next time don't test on production, we are consumers on the other side. And don't call this garbage ISA D3D12 compatible when it clearly isn't.
Following this trend, Xe2 will never get the CPU overhead fix, as magically Xe2 won't meet the minimum requirements of management to give a damn at all.

Disgusting.
