### ISSUE TITLE
Diablo II - Resurrected Alpa, Beta

### ISSUE THREAD

**Issue by Valkirie** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#78]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Diablo II Resurrected Alpha, Beta

---
#### Game Platform [Required]
- [ ] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [X] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
Intel® Core™ i7-1165G7

---
#### GPU Driver Version [Required]
- [X] 30.0.100.9805 (*latest*)
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 11 (*Insider Preview*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. Start the game.
2. Game will instantly crash.
3. 

---
#### Device / Platform [Optional][Recommended]

One X Player

**Comment by gennro** [comment]
Exact same issue on gpd win3 device, the game is DX12 though not DX11. Tried VKD3D dll binaries to see if I could get the game to run using DX12 to Vulkan and no luck that way.

**Comment by Valkirie** [comment]
I was able to get into the game with **27.20.100.9616** but performance was terrible (_6fps in the menu_) unless setting device power profile to performance. Otherwise it appears the Intel Xe is not ramping up properly in frequency, staying below 400Mhz while GPU usage still is 100%.
![image](https://user-images.githubusercontent.com/934757/129765853-92ac6e93-6961-4dfb-b962-1d05fb8b9d66.png)

**Comment by Saracchini** [comment]
Testing with GPD Win3 Here, 9466 drivers. It crashes. I'll test the newer ones.

**Comment by iAmGhost** [comment]
Owner of [this video](https://www.youtube.com/watch?v=Y8zuYTvnLhw) said game works well with minor video glitch on Windows 10 19H1(=1903).

**Comment by Valkirie** [comment]
> Owner of [this video](https://www.youtube.com/watch?v=Y8zuYTvnLhw) said game works well with minor video glitch on Windows 10 19H1(=1903).

Interesting. You might want to task that guy which driver build he's running.

**Comment by iAmGhost** [comment]
> > Owner of [this video](https://www.youtube.com/watch?v=Y8zuYTvnLhw) said game works well with minor video glitch on Windows 10 19H1(=1903).
> 
> Interesting. You might want to task that guy which driver build he's running.

They confirmed it's 30.0.100.9805.

**Comment by Valkirie** [comment]
> > > Owner of [this video](https://www.youtube.com/watch?v=Y8zuYTvnLhw) said game works well with minor video glitch on Windows 10 19H1(=1903).
> > 
> > 
> > Interesting. You might want to task that guy which driver build he's running.
> 
> They confirmed it's 30.0.100.9805.

Language then ... ?

**Comment by iAmGhost** [comment]
> Language then ... ?

Language were set to Korean but I don't it's matter since they also confirmed it's not working on 21H1 with same driver.

**Comment by Valkirie** [comment]
> > Language then ... ?
> 
> Language were set to Korean but I don't it's matter since they also confirmed it's not working on 21H1 with same driver.

Brillant. Let me raise awareness to Intel then.

**Comment by Saracchini** [comment]
Release version do not crash anymore. Game runs very stable with 9864. 
There are the same issues in [MechWarrior 5](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/74) and the Ascent, when you change resolution scale in-game. The solution is also the same as for these games: switch the graphic options until the problem fix itself. Issues are: blank/black screen , heavily tinted or with strong graphical glitches. It never happens when you first load the game.

**Comment by Saracchini** [comment]
Graphic Issues persist with latest 1069 driver. 
Some graphic glitches (colored squares on button graphics, etc) seems to be slightly worse. Game is still playable.

**Comment by Saracchini** [comment]
Graphic Issues persists with latest 1121 driver.

**Comment by estebanr863** [comment]
Hi all,

We were able to reproduce the graphical corruption and they have now been moved the issue to our driver development team. Please do note that it might take from 3 to 6 months for a possible fix to be included in a driver release.

**Comment by Saracchini** [comment]
Issues got actually worse with 1340 driver. 
The ground now shows white pixelated texture, and graphic effects like auras lack transparency.

**Comment by kristheb** [comment]
can confirm. no transparency anymore after changing to version 30.0.101.1340

**Comment by Saracchini** [comment]
Issue persists with 1404 driver.

**Comment by Saracchini** [comment]
Issue persists with 1994 driver.

**Comment by Valkirie** [comment]
Issue persists with 30.0.101.1314. Transparency on SFX is broken.

**Comment by Valkirie** [comment]
I believe issue is fixed with 31.0.101.3222. Will do more tests.

**Comment by Saracchini** [comment]
I can confirm that it is not fixed. Act5 starting point has very glitched shadows, as well the aura effects of a Paladin character are not transparent.

**Comment by EstebanIntel** [comment]
Hi @Valkirie and @Saracchini, a possible fix for this issue is included with driver [31.0.101.4369](https://www.intel.com/content/www/us/en/download/726609/779145/intel-arc-iris-xe-graphics-whql-windows.html). Can you please test it?

**Comment by Saracchini** [comment]
Hi. Unfortunately I do not have a Intel device with the XE GPU anymore, so I'll be unable to confirm.

**Comment by EstebanIntel** [comment]
That's a shame. Since this is fixed in our lab tests, can this issue be closed?

**Comment by EstebanIntel** [comment]
Hi @IGCIT, we are not seen this issue in our lab on the latest driver. @Saracchini is not able to test, and @Valkirie is not responding. Can this issue be closed?
