### ISSUE TITLE
Screen recording not working in either the snipping tool or with loom. just crashes after a second

### ISSUE THREAD

**Issue by fedbwas** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#852]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Snipping tool

### Processor / Processor Number [Required]

i7 1360P

### Graphic Card [Required]

A370

### GPU Driver Version [Required]

32.0.101.6078

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

Can't screen record

### Description and steps to reproduce [Required]

Snipping tool and loom - neither work

### Device / Platform

HP envy x360 16f2

**Comment by fedbwas** [comment]
hi ilya! 

well i've double checked and i'm on 
13th gen intel(r) core(tm) 17-1360p
inte(r) iris(r)xe directX 12 (FL12.1)
intel(r)arc(tm)A370M driver version 32.0.101.6078

ssu log here 
[ssu log 24.10.2.txt](https://github.com/user-attachments/files/17227825/ssu.log.24.10.2.txt)

i've just tried again and it still wont work but only in a specific situation
i am trying to screen record an issue when using arc browser (based on chromium) where for some website (twitter.com;seriouseats.com) the webpage doesn't register mouse clicks. i can scroll and i can close the browser but anything within the webpage doesn't click through. when i try to screen record then, then countdown starts and reaches zero but then the app crashes. same thing happens on loom. i am in contact with arc support as well.

**Comment by Ilya-intel** [comment]
@fedbwas 
Thanks for clarifying, I'm doing tests right now and I also see the issue, but not on all laptops that I have.
Anyway, I'll dig deeper and let you know the progress.

**Comment by Ilya-intel** [comment]
Hey @fedbwas ,
Could you try lowering resolution of the screen and use snipping tool in Arc Browser as a matter of testing?
I tried lowering from 4k to 2k and no crashes were observed. I wanted to get double confirmation from your side also.

**Comment by fedbwas** [comment]
Hi Ilya, 

Now I've just tried both and it worked both times! Does that mean the issue is resolved?
i'm still on 32.0.101.6078, so I don't know what's changed

**Comment by Ilya-intel** [comment]
@fedbwas 
Interesting, my test laptop still crashing :)
It might be caused by some OS update. Anyway, let's keep this one open until we have 100% confirmation of the fix.
I'll continue testing.

**Comment by Ilya-intel** [comment]
Hey @fedbwas ,
My issue also magically disappears, I've noticed it happened after several OS updates.
Are you still not experiencing crashes with the Snipping Tool?

**Comment by fedbwas** [comment]
Yes, I haven't experienced a crash since!

**Comment by Ilya-intel** [comment]
@fedbwas 
Great, then I'll be closing this thread.
Feel free to open the new one if the issue comes back.
