### ISSUE TITLE
B580 VRAM Tuning does not re-apply automatically after system reboot.

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#906]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

intel Graphics Software

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc B580

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[SSU_20241218.txt](https://github.com/user-attachments/files/18197737/SSU_20241218.txt)

### Description and steps to reproduce [Required]

In the intel Graphics Software, I set the VRAM speed from 19Gbps to 20Gbps and then apply it. It was successful and both GPU-Z and benchmark apps could verify the result.

However, after system reboot, even though it showed 20Gbps in the intel Graphics Software, both GPU-Z and benchmarks showed that the VRAM was actually running at 2375MHz (19Gbps), while the GPU Tuning parameters (Voltage Limit, Power Limit, and Frequency Offset) were re-applied correctly.

The intel Graphics Software can "remember" all the user configurations, but only the VRAM Tuning is not re-applied after reboot.

**Comment by Susie1818** [comment]
After some further experiments, I think I've found sort of a root cause for this.

The VRAM Tuning seems to have some limitations on the current version of intel Graphics Software. It cannot successfully apply the change if the amount of change is not small enough. For example, a jump from 19 to 20, after you hit the "Apply Changes" button, won't do anything. Even from 19 to 19.5 it won't do anything, either. I had to make the changes from 19 to 19.25, apply, then 19.25 to 19.5, apply, then 19.5 to 19.75, apply, then finally 19.75 to 20, and apply. Only by these small increments it would be applied successfully.

And then, after reboot, it would naturally fail because it tried to re-apply 20Gbps, but a jump dirrectly from 19Gbps was not accepted. Nevertheless, the UI seems to be unaware at all if some of the changes were not applied successfully. Meh~

Anyway, the outcome is kind of silly for now.

**Comment by Felipe-Intel** [comment]
Hello @Susie1818
We submitted some internal tickets for misbehaviors of the tuning options, including one with the VRAM tuning.  I'll go ahead and try to reproduce this as well in our lab. I'll keep you posted. Could you please you try one of the accepted values, reboot the system and let me know if the setting persists?

**Comment by Susie1818** [comment]
@Felipe-Intel 
> try one of the accepted values, reboot the system and let me know if the setting persists

I just tried 19.25, didn't accept (stayed at 2375MHz), 19.2, accepted (metrics→2400MHz), rebooted, no good (2375MHz on the metrics despite the VRAM Tuning kept the setting 19.2Gbps).

**Comment by Felipe-Intel** [comment]
Hello @Susie1818 we released a driver yesterday with a new version of IGS. I was testing on my side and the values persisted after reboot. We are still working out the small steps/big steps issue. Could you please check on your side if this issue is solved (i.e. tuning not re-applying after reboot).

**Comment by Susie1818** [comment]
@Felipe-Intel 

I tried but the issue is still there, not re-applying 20Gbps after reboot even though the UI remembers the value of 20.

**Comment by SavageWaffle** [comment]
Fix TBD

**Comment by Felipe-Intel** [comment]
@SavageWaffle this is still under investigation

**Comment by Felipe-Intel** [comment]
Yes, I was testing in the lab before coming here, but now that you confirmed, is it ok if we close this ticket?

**Comment by Susie1818** [comment]
Yes, I think it is fine to close this ticket.
